'use strict';

/*
 * QMS English lexicon — category labels and term translations for the
 * Wan Wu correspondence tables and module readings. Loaded before app.js;
 * merged into KEY_EN / EN_VOCAB at startup.
 */

window.QMS_KEY_EN = {
  '核心描述': 'Core description', '默认宫位': 'Default palace', '阴阳': 'Polarity',
  '吉凶': 'Auspice', '五行': 'Element', '类象': 'Imagery', '旺衰': 'Prosperity cycle',
  '临宫': 'In-palace effects', '常见组合': 'Common combinations', '天时': 'Weather & timing',
  '行业': 'Industries', '工作': 'Occupations', '职业': 'Occupations', '代表人物': 'Representative people',
  '身体疾病': 'Body & ailments', '自然天象': 'Natural phenomena', '天象自然': 'Natural phenomena',
  '场所环境': 'Places & settings', '物品器具': 'Objects & utensils', '器物物品': 'Objects & utensils',
  '事业行为': 'Activities', '事件行为': 'Events & actions', '占断适宜': 'Favourable for',
  '占断不宜': 'Unfavourable for', '占断含义': 'Divination meaning', '感觉': 'Sensations',
  '五味': 'Tastes', '气候': 'Climate', '脏腑': 'Organs', '谒见': 'Audiences',
  '谋旺': 'Prospering pursuits', '歌诀': 'Verse', '河图数': 'Hetu numbers', '洛书数': 'Luoshu numbers',
  '生我': 'Feeds me', '我生': 'I feed', '生产': 'Production', '求名': 'Seeking fame',
  '求利': 'Seeking profit', '自刑': 'Self-punishment', '名称': 'Name',
};

window.QMS_TERMS_EN = {
  // ---- palaces / structural ----
  '一宫坎': 'Palace 1 Kan', '二宫坤': 'Palace 2 Kun', '三宫震': 'Palace 3 Zhen', '四宫巽': 'Palace 4 Xun',
  '五宫中': 'Palace 5 Center', '六宫乾': 'Palace 6 Qian', '七宫兑': 'Palace 7 Dui', '八宫艮': 'Palace 8 Gen',
  '九宫离': 'Palace 9 Li', '阴星': 'Yin star', '阳星': 'Yang star', '病星': 'sickness star',
  '东方': 'east', '西方': 'west', '南方': 'south', '北方': 'north', '中央地带': 'central zone',
  '大凶': 'very inauspicious', '大吉': 'very auspicious', '可见': 'visible', '可成': 'achievable',
  '可行': 'feasible', '难成': 'hard to achieve', '易生': 'easily arises', '阻隔': 'blockage',
  '戊土': 'Wu Earth', '己土': 'Ji Earth', '辛金': 'Xin Metal', '阴土': 'Yin Earth', '阳土': 'Yang Earth',
  // ---- tastes / sensations ----
  '酸': 'sour', '甘': 'sweet', '咸': 'salty', '苦': 'bitter', '辣': 'spicy', '苦辣': 'bitter-spicy',
  '热': 'hot', '烫': 'scalding', '痒': 'itchy', '辛辣': 'pungent',
  // ---- body & ailments ----
  '心': 'heart', '肾': 'kidneys', '肝': 'liver', '足': 'feet', '大脑': 'brain', '血压': 'blood pressure',
  '肩': 'shoulders', '肩膀': 'shoulders', '手足': 'hands & feet', '手臂': 'arms', '左肩': 'left shoulder',
  '头部': 'head', '头发': 'hair', '耳朵': 'ears', '牙': 'teeth', '口腔': 'mouth', '气管': 'windpipe',
  '呼吸系统': 'respiratory system', '浮肿部位': 'swollen areas', '炎症部位': 'inflamed areas',
  '心脏病': 'heart disease', '肾病': 'kidney disease', '泌尿疾病': 'urinary ailments',
  '口腔疾病': 'oral ailments', '腹泻': 'diarrhoea', '皮肤病': 'skin disease', '疮疡': 'sores',
  '慢性病': 'chronic illness', '传染病': 'infectious disease', '瘟疫': 'plague', '疼痛': 'pain',
  '跌打外伤': 'traumatic injuries', '肝胆疾病': 'liver & gallbladder illness', '内科疾病': 'internal illness',
  '器质病变': 'organic lesions', '主贵人相助可愈': 'healed with a benefactor’s help', '病情不重': 'illness not severe',
  // ---- people ----
  '男': 'male', '女': 'female', '男人': 'man', '女人': 'woman', '父亲': 'father', '小孩': 'children',
  '商人': 'merchants', '孕妇': 'pregnant women', '情人': 'lover', '当权者': 'those in power',
  '有指挥能力之人': 'commanders', '脾气暴躁之人': 'hot-tempered people', '化工工人': 'chemical workers',
  '司炉工': 'stokers', '电厂工作者': 'power-plant workers', '媒体人': 'media people', '演说家': 'orators',
  '帝王': 'emperors', '权贵': 'the powerful', '公关部': 'PR department', '病人': 'patients',
  '庸医': 'quack doctors', '巫婆': 'witches', '农妇': 'farm women', '阴柔小人': 'sly schemers',
  '术士': 'occultists', '药师': 'pharmacists', '护士': 'nurses', '伤者': 'the injured',
  '猎人': 'hunters', '对手': 'opponents', '肇事者': 'culprits', '兄长': 'elder brothers',
  '执法机构人员': 'law-enforcement staff', '讨债人': 'debt collectors', '伤心人': 'the heartbroken',
  '受伤者': 'injury victims', '出租车司机': 'taxi drivers', '上司': 'superiors', '一把手': 'top boss',
  '尊长': 'elders & seniors', '恩人': 'benefactors', '明星': 'celebrities', '教授': 'professors',
  '经理': 'managers', '管理者': 'administrators', '负责人': 'persons in charge', '宗教领袖': 'religious leaders',
  '顶头上司': 'immediate boss', '监考官': 'invigilators', '裁判': 'referees', '原告': 'plaintiffs',
  '放债人': 'moneylenders', '核心人物': 'key figures', '仙佛': 'immortals & buddhas',
  '直属领导': 'direct leader', '家庭主妇': 'housewives', '武将': 'generals', '武士': 'warriors',
  '渔民': 'fishermen', '消防员': 'firefighters', '检察官': 'prosecutors', '总统': 'presidents',
  '学者': 'scholars', '妓女': 'prostitutes', '奴婢': 'servants', '匪徒': 'bandits',
  '地产商': 'property developers', '演艺人员': 'entertainers', '歌星': 'pop singers',
  '宗教人士': 'religious people', '学员': 'students', '刑警': 'detectives', '军营': 'barracks',
  // ---- character traits ----
  '表现': 'expressiveness', '希望': 'hope', '雄威': 'mighty', '刚猛': 'fierce', '热烈': 'ardent',
  '急速': 'rapid', '明亮': 'bright', '光明磊落': 'upright & open', '慷慨': 'generous',
  '外向': 'extroverted', '火烈': 'fiery', '清廉': 'incorruptible', '体恤': 'considerate',
  '正面': 'positive', '多言': 'talkative', '激情': 'passion', '暴烈': 'violent', '强悍': 'tough',
  '正义': 'righteous', '愤怒': 'anger', '性急': 'impatient', '果断': 'decisive', '暴躁': 'irascible',
  '好表现': 'showy', '自恋': 'narcissistic', '躁动': 'restless', '表演欲': 'urge to perform',
  '批判欲': 'urge to criticise', '狂热': 'fanatical', '好猜忌': 'suspicious-minded', '细心': 'attentive',
  '慈祥': 'kindly', '善照顾': 'caring', '懦弱': 'timid', '慢性': 'chronic', '迟钝': 'sluggish',
  '内向': 'introverted', '修行': 'spiritual practice', '沉静内敛': 'quiet & reserved',
  '封闭自守': 'closed-off', '一根筋': 'one-track mind', '认真严肃': 'earnest & serious',
  '练死劲': 'brute-force effort', '钻牛角尖': 'splitting hairs',
  '用功读书但未必高分': 'studies hard but not always high marks',
  '好动': 'restless', '争强好胜': 'fiercely competitive', '直率': 'forthright', '冲动': 'impulsive',
  '不计后果': 'heedless of consequences', '性情直爽': 'straightforward nature', '鲁莽冲动': 'rash',
  '易怒': 'quick-tempered', '悲伤': 'sorrowful', '粗野': 'coarse', '恐惧': 'fear', '难看': 'ugly',
  '丑陋': 'hideous', '健壮': 'robust', '面部少有笑容': 'rarely smiles', '高贵的': 'noble',
  '高档的': 'high-class', '稀有的': 'rare', '有组织能力的': 'organised', '名牌的': 'brand-name',
  '重点的': 'key', '高尚的': 'lofty', '有影响力的': 'influential', '服众的': 'commanding respect',
  '威严的': 'dignified', '德高望重的': 'venerable', '愁闷': 'melancholy', '第一': 'first',
  '有管理权': 'managerial authority', '地位显赫': 'eminent status', '高大上': 'high-end',
  '甲被隐藏': 'Jia stays hidden', '尊贵威严': 'noble & dignified', '守信正直': 'trustworthy & upright',
  '有领袖气质': 'leaderly presence', '气概雄伟': 'grand bearing', '文韬武略': 'mastery of pen & sword',
  '品质高雅': 'refined character', '态度安然': 'composed manner', '庄严矍铄': 'solemn & hale',
  '喜悦': 'joy', '善良': 'kind', '善变': 'fickle', '多情': 'amorous', '多愁善感': 'sentimental',
  '忠厚老实': 'honest & sincere', '心思缜密': 'meticulous mind', '性格内向': 'introverted nature',
  '沉稳': 'composed', '深沉': 'deep', '柔和': 'mild', '刚烈': 'fierce & unyielding',
  '能言善辩': 'eloquent', '正直': 'upright', '安稳': 'stable', '好面子': 'face-conscious',
  '阴柔沉静': 'soft & still', '感性敏锐': 'sensitive & keen', '犹豫': 'hesitant', '多幻想': 'dreamy',
  '好猜疑': 'distrustful', '智谋': 'resourceful', '机敏': 'quick-witted', '敬业': 'diligent',
  '容易涉及阴谋': 'prone to intrigue', '怕事': 'timid of trouble', '不能自主': 'lacking autonomy',
  '善于策划': 'good at scheming', '女性化气质': 'feminine temperament',
  // ---- physique ----
  '体型丰满': 'plump build', '圆脸': 'round face', '少胡须': 'sparse beard', '短发': 'short hair',
  '皮肤白里透红': 'rosy fair skin', '方脸': 'square face', '粗眉': 'thick brows', '重发': 'thick hair',
  '鼻子直大': 'straight large nose', '嘴唇方而有棱角': 'angular lips', '唇线清晰': 'defined lip line',
  '身材长直': 'tall straight build', '敦厚': 'stocky & honest', '形端方': 'upright form',
  '矮小黑丑': 'short, dark & plain', '圆脸瘦肩': 'round face, narrow shoulders', '声调不高': 'soft-spoken',
  // ---- in/out of season ----
  '得令时成绩辉煌': 'brilliant results in season', '失令时容易灰心丧气': 'easily disheartened out of season',
  '可成大材但持久性差': 'great potential but poor staying power',
  '得令时狐假虎威': 'borrowed authority in season', '失令时灰心乞怜': 'dispirited begging out of season',
  '得令时为栋梁': 'a pillar in season', '失令时为闲置材料': 'idle timber out of season',
  '过旺则伤': 'excess brings injury', '物极必反': 'extremes invert', '极盛': 'zenith',
  '鼎盛': 'prime', '最强状态': 'peak state',
  // ---- weather & nature ----
  '烈日': 'blazing sun', '云': 'clouds', '月亮': 'moon', '星星': 'stars', '暴雨': 'rainstorms',
  '大风': 'gales', '大雨': 'heavy rain', '多云': 'cloudy', '冰': 'ice', '炎热': 'sweltering',
  '雨天': 'rainy days', '霞光': 'rosy glow', '彩虹': 'rainbow', '晴朗': 'clear skies',
  '祥瑞': 'auspicious omens', '日光': 'sunlight', '风和日丽': 'mild & sunny', '浓雾': 'thick fog',
  '地气潮湿': 'damp ground', '泥泞': 'muddy', '细雨': 'drizzle', '露水': 'dew', '冰雾': 'icy fog',
  '春雷': 'spring thunder', '雷电': 'thunder & lightning', '地震': 'earthquakes', '洪水': 'floods',
  '阴雨': 'overcast rain', '湿润': 'moist',
  // ---- places ----
  '高岭': 'high ridges', '冶炼场': 'smelters', '冶炼厂': 'smelting plants', '煤炭': 'coal',
  '电厂': 'power plants', '明亮场所': 'bright places', '城门': 'city gates', '宫室': 'palaces',
  '剧场': 'theatres', '向阳之地': 'sunny ground', '药店': 'pharmacies', '田野': 'open fields',
  '农村': 'countryside', '旧屋': 'old houses', '病房': 'sickrooms', '停尸房': 'morgues',
  '竞技场': 'arenas', '事故现场': 'accident scenes', '破坏的道路': 'broken roads',
  '危险的环境': 'dangerous places', '悬崖': 'cliffs', '屠宰厂': 'slaughterhouses', '兵工厂': 'arsenals',
  '警察局': 'police stations', '检察院': 'procuratorates', '危险品生产存放地': 'hazardous-goods sites',
  '政府机关': 'government offices', '高档场所': 'upscale venues', '总部': 'headquarters',
  '中心': 'centres', '办公大楼': 'office towers', '古建筑': 'ancient buildings', '庙宇': 'temples',
  '首饰店': 'jewellery shops', '古董行': 'antique dealers', '金矿': 'gold mines', '煤矿': 'coal mines',
  '油矿': 'oil fields', '首府': 'capital seats', '湖泊': 'lakes', '湖海': 'lakes & seas',
  '江河': 'rivers', '江河湖海': 'rivers & seas', '河流': 'rivers', '水池': 'pools',
  '水边': 'waterside', '墓地': 'graveyards', '教堂': 'churches', '歌厅': 'karaoke halls',
  '游乐场': 'amusement parks', '办公室': 'offices', '暗室': 'dark rooms', '山林': 'mountain forests',
  '山岚': 'mountain mists', '土地': 'land', '地下水': 'groundwater', '图书馆': 'libraries',
  '书店': 'bookshops', '湿地': 'wetlands', '水塔': 'water towers', '地沟': 'gutters',
  '地井': 'wells', '污水': 'sewage', '粪池': 'cesspools', '污秽场所': 'filthy places',
  '泉水': 'springs', '溪流': 'streams', '温泉': 'hot springs', '阴暗低洼': 'dark hollows',
  '北方水边': 'northern waterside', '围墙': 'walls', '城墙': 'city walls',
  // ---- objects ----
  '灯光': 'lamplight', '能源': 'energy', '热源': 'heat sources', '光芒': 'radiance', '权力': 'power',
  '温暖': 'warmth', '色彩': 'colours', '变幻': 'shifting change', '影视': 'film & TV', '传媒': 'media',
  '名气': 'fame', '光亮之物': 'shiny things', '灶': 'stoves', '发热之物': 'heat-producing things',
  '有柄之物': 'handled objects', '饼干': 'biscuits', '火箭': 'rockets', '大炮': 'cannons',
  '变压器': 'transformers', '窗户': 'windows', '小火炉': 'small stoves', '暖气片': 'radiators',
  '吊灯': 'chandeliers', '荧幕': 'screens', '广告牌': 'billboards', '影视设备': 'film equipment',
  '照明器具': 'lighting fixtures', '药物': 'medicines', '药': 'medicine', '棺材': 'coffins',
  '丧服': 'mourning clothes', '农具': 'farm tools', '医疗物': 'medical items', '纠正物': 'corrective items',
  '问题物': 'faulty items', '损坏物': 'damaged goods', '坏电器': 'broken appliances',
  '破裂屏幕': 'cracked screens', '土生物': 'earth-born things', '家禽': 'poultry',
  '外表很好内部损坏': 'fine outside, broken inside', '地面交通工具': 'ground vehicles',
  '轿车': 'sedans', '车船': 'vehicles & boats', '船只': 'boats', '攻击物': 'weapons of attack',
  '证书': 'certificates', '官方文件': 'official documents', '贵重物品': 'valuables', '钱币': 'coins',
  '名贵古董': 'precious antiques', '钻石': 'diamonds', '名人字画': 'famous calligraphy & paintings',
  '名贵艺术品': 'precious artworks', '高档家具': 'fine furniture', '玉玺': 'imperial seals',
  '符': 'talismans', '国旗': 'national flags', '帽徽': 'cap insignia', '领徽': 'collar insignia',
  '委任状': 'letters of appointment', '丝麻布帛': 'silks & linens', '诏书': 'imperial edicts',
  '宴会': 'banquets', '石头': 'stones', '瓷器': 'porcelain', '陶瓷': 'ceramics', '椅子': 'chairs',
  '帽子': 'hats', '字画': 'calligraphy & paintings', '书画': 'calligraphy & painting', '图片': 'pictures',
  '坚果': 'nuts', '五谷': 'grains', '油漆': 'paint', '汤': 'soup', '烟囱': 'chimneys',
  '火炉': 'furnaces', '暗器': 'hidden weapons', '墨水茶壶': 'ink & teapots',
  // ---- food ----
  '烧烤': 'barbecue', '热食': 'hot food', '辛辣食品': 'spicy food', '海带': 'kelp',
  // ---- plants & animals ----
  '凤凰': 'phoenix', '孔雀': 'peacock', '雉鸡': 'pheasant', '带柄果实': 'stemmed fruits',
  '梨子': 'pears', '樱桃': 'cherries', '西瓜': 'watermelon', '南瓜': 'pumpkin', '莲蓬': 'lotus pods',
  '向日葵': 'sunflowers', '牡丹': 'peonies', '辣椒': 'chillies', '大红花': 'big red flowers',
  '蚊子': 'mosquitoes', '猎狗': 'hunting dogs', '夜猫': 'night owls', '狮虎': 'lions & tigers',
  '藏獒': 'Tibetan mastiffs', '老虎': 'tigers', '金龙鱼': 'arowana', '燕鱼': 'angelfish',
  '名贵稀有的动物': 'rare precious animals', '名贵稀有的树种和花木': 'rare trees & flowers',
  '金丝楠木': 'golden nanmu', '红木': 'rosewood', '君子兰': 'clivia', '玫瑰花': 'roses',
  '果树': 'fruit trees', '荷花': 'lotus', '大树': 'big trees', '刺猬': 'hedgehogs', '熊': 'bears',
  '水鸟': 'waterfowl', '浮萍': 'duckweed', '泽中之物': 'marsh creatures',
  // ---- events & activities ----
  '丧葬': 'funerals', '就医问病': 'seeking treatment', '农牧': 'farming & herding',
  '保守经营': 'conservative business', '看病': 'medical visits', '吊丧': 'condolences',
  '收债': 'collecting debts', '畜牧': 'livestock raising', '容易得病': 'prone to illness',
  '出毛病': 'develops faults', '出问题': 'problems arise', '不利用兵': 'bad for military action',
  '可去拜师学艺': 'good for apprenticeship', '交友': 'making friends', '问题': 'problems',
  '麻烦': 'trouble', '解决问题': 'solving problems', '处理麻烦': 'handling trouble',
  '批判指正': 'critique & correction', '医疗': 'healthcare', '中小学老师': 'schoolteachers',
  '卫生业': 'sanitation', '肉品加工': 'meat processing', '震动': 'vibration', '运动': 'movement',
  '容易受伤': 'injury-prone', '刑伤': 'punishment injuries', '经商破财': 'business losses',
  '出行有灾': 'travel mishaps', '伤灾': 'injuries', '跑动': 'running', '响声': 'noises',
  '伤害': 'harm', '残疾': 'disability', '战争': 'war', '残缺不全的': 'incomplete things',
  '进攻部队': 'assault troops', '受伤': 'injury', '伤心': 'heartbreak', '伤痛': 'pain',
  '损害': 'damage', '消耗': 'depletion', '抓捕': 'arrests', '索取': 'demands', '戏耍': 'play',
  '收敛财货': 'gathering goods', '渔猎': 'fishing & hunting', '格斗': 'combat', '散打': 'kickboxing',
  '拳击': 'boxing', '冲锋': 'charging', '引诱': 'enticement', '对抗性': 'confrontational',
  '竞技性': 'competitive', '追债讨账': 'debt collection', '维权': 'rights defence',
  '军事行动': 'military operations', '追债': 'debt chasing', '讨账': 'collecting accounts',
  '索赔': 'claims', '出行赶急路': 'urgent travel', '捕鱼': 'fishing', '博彩': 'betting',
  '捕捉盗贼': 'catching thieves', '博弈': 'gaming', '安葬': 'burial', '修造': 'construction',
  '安宁之事': 'peaceful matters', '赴任': 'taking office', '营建': 'building', '升迁': 'promotion',
  '嘉奖': 'commendation', '贵人提携': 'a benefactor’s patronage', '得到帮助': 'receiving help',
  '获得权力': 'gaining power', '逢凶化吉': 'turning peril into fortune',
  '所求有贵人相助': 'aided by benefactors', '主吉利顺遂': 'augurs smooth fortune',
  '凡事遇值符减凶增吉': 'the Chief tempers ill and boosts good', '投资': 'investment',
  '策划': 'planning', '出谋划策': 'devising strategies', '演说': 'oratory', '庆典': 'celebrations',
  '广告': 'advertising', '搬迁': 'relocation', '捕盗': 'catching thieves', '建造': 'building',
  '开拓': 'pioneering', '治病': 'curing illness', '求医': 'seeking doctors', '争讼': 'litigation',
  '官非': 'legal trouble', '隐藏': 'concealment', '潜伏': 'lurking', '暧昧': 'ambiguous affairs',
  '暗中行事': 'acting covertly', '怀孕': 'pregnancy', '征战': 'campaigns', '文化': 'culture',
  '文字': 'writing', '文明': 'civilisation', '与疾病有关': 'illness-related', '宗教': 'religion',
  '寺庙宗教': 'temples & religion', '诸神之元神': 'primal spirit of the gods',
  '八神九星之领袖': 'leader of deities & stars', '至神之神': 'supreme deity', '天乙贵人': 'Tianyi noble',
  '万会至尊': 'paramount of assemblies', '百恶消散': 'all evils dispersed', '诸凶寂灭': 'all menace extinguished',
  // ---- colours ----
  '黑色': 'black', '白色': 'white', '黄色': 'yellow', '红色': 'red', '绿色': 'green', '青色': 'cyan',
  '赤色': 'crimson', '棕': 'brown', '碧绿': 'jade green', '黄黑': 'yellow-black', '黄土色': 'earthy yellow',
  '绚烂': 'resplendent', '五彩缤纷': 'riot of colour',
  // ---- yin-water (Gui) imagery from the modal ----
  '情欲': 'desire', '制约': 'restraint', '管束': 'discipline', '艰难困苦': 'hardship',
  '跋涉': 'trekking', '变动': 'change', '变化': 'transformation', '性': 'sexuality', '淫': 'lust',
  '石油': 'petroleum', '暗中所干之事': 'covert dealings', '取象最末端': 'the last in imagery',
  '上瘾不能摆脱': 'inescapable addiction', '网瘾': 'internet addiction', '性瘾': 'sex addiction',
  '一切成瘾': 'all addictions', '运动缓慢或静止不动的液体': 'slow or still liquids', '鬼': 'ghosts',
  '私处': 'private parts', '静脉': 'veins', '眼球': 'eyeballs', '痣': 'moles', '口水': 'saliva',
  '眼泪': 'tears', '鼻涕': 'mucus', '汗液': 'sweat', '尿溺': 'urine', '经血': 'menses',
  '津液': 'bodily fluids', '精血': 'essence & blood',
};

/* Batch 2 — full Wan Wu symbol-block vocabulary (water/fire/wood/metal/earth
   stems, all nine stars, eight gates, eight deities, trigram palaces). */
Object.assign(window.QMS_TERMS_EN, {
  '井水': 'well water', '墨池': 'ink ponds', '泳池': 'swimming pools', '瓜农': 'melon growers',
  '菜农': 'vegetable growers', '茶农': 'tea growers', '淫荡之人': 'lecherous people', '囚犯': 'prisoners',
  '被困之人': 'the trapped', '穷困潦倒之人': 'the destitute', '隐士': 'hermits', '智者': 'the wise',
  '占卜者': 'diviners', '阴谋家': 'schemers', '水利工人': 'waterworks workers', '清洁工': 'cleaners',
  '鸬鹚': 'cormorants', '雁': 'wild geese', '鹉': 'parrots', '鹭': 'herons', '黑蝇': 'black flies',
  '蛙': 'frogs', '水中小型动物': 'small aquatic animals', '水稻': 'rice', '水仙': 'narcissus',
  '喜水植物': 'water-loving plants', '菖蒲': 'calamus', '蕨类': 'ferns', '喜阴植物': 'shade plants',
  '甘露': 'sweet dew', '饮品': 'drinks', '粥': 'porridge', '沥青': 'asphalt', '液体': 'liquids',
  '浑浊的水': 'turbid water', '水具': 'water vessels', '鞋': 'shoes', '雨露': 'rain & dew',
  '结晶': 'crystals', '墨': 'ink', '墨水': 'ink', '笔洗': 'brush washers', '腌制品': 'pickled goods',
  '麻凉': 'numbing-cool', '咸浊': 'salty-murky', '中平小凶': 'neutral, mildly inauspicious',
  '冲动之人': 'impulsive people', '时髦之人': 'fashionable people', '盛夏烈日炎炎': 'midsummer blazing sun',
  '容易急躁': 'prone to impatience', '易有血光之灾': 'risk of bloodshed', '小凶(中平偏凶)': 'mildly inauspicious',
  '橙': 'orange', '血脉': 'blood vessels', '火伤': 'burns', '烫伤': 'scalds', '血热': 'blood heat',
  '头面疮疡': 'head & face sores', '性急之人': 'impatient people', '华而不实者': 'the flashy & hollow',
  '炉灶匠人': 'stove craftsmen', '外表华丽': 'splendid exterior', '性烈如火': 'fiery temper',
  '多才但难持久': 'talented but inconstant', '好大喜功': 'craves grand feats', '虎头蛇尾': 'strong start, weak finish',
  '火烧云': 'sunset clouds', '彩霞': 'rosy clouds', '干旱': 'drought', '火灾': 'fires',
  '晴热': 'hot & clear', '灯笼': 'lanterns', '烟花爆竹': 'fireworks', '华丽衣物': 'splendid clothing',
  '窑炉': 'kilns', '灯火辉煌处': 'brightly lit places', '剧院': 'theatres', '展览馆': 'exhibition halls',
  '炼钢厂': 'steelworks', '加油站': 'petrol stations', '文艺表演': 'performances', '绘画': 'painting',
  '装修': 'renovation', '照明': 'lighting', '消防': 'firefighting', '冶炼': 'smelting',
  '广告宣传': 'advertising', '文化活动': 'cultural events', '照明工程': 'lighting engineering',
  '若得吉格可主文明文章': 'with good patterns, augurs culture & writing', '利于出谋划策': 'good for strategising',
  '利见大人': 'favourable to meet the great', '不利于求财': 'bad for seeking wealth', '考官': 'examiners',
  '亮丽': 'radiant', '好看': 'good-looking', '漂亮': 'pretty', '英俊': 'handsome', '才华': 'talent',
  '大方': 'gracious', '燥热': 'scorching', '表象': 'appearances', '自恋自信': 'vain confidence',
  '热情明朗': 'warm & sunny', '虚荣浮夸': 'vain & showy', '易怒好胜': 'irritable & competitive',
  '公关社交': 'PR & socialising', '靠形象人设': 'image-based persona', '好看亮丽': 'striking looks',
  '演艺': 'show business', '社交': 'socialising', '公关': 'public relations', '模特': 'models',
  '照亮': 'illumination', '电子电器': 'electronics', '电视电脑': 'TVs & computers', '火业': 'fire trades',
  '亮丽物': 'radiant things', '明显物': 'conspicuous things', '妆容': 'makeup', '烟花': 'fireworks',
  '锦鲤': 'koi', '热带鱼': 'tropical fish', '热闹场所': 'lively places', '阳光物': 'sunny things',
  '能源物': 'energy objects', '阳台': 'balconies', '电站': 'power stations', '眼看物': 'eye-catching things',
  '书': 'books', '电脑': 'computers', '大吉(三吉门之一)': 'very auspicious (one of the three lucky gates)',
  '万物复苏': 'all things revive', '掌管财经机关': 'governs financial bodies',
  '多和钱财利润房产和土地有关': 'tied to money, profit, property & land', '房产': 'property',
  '工资收入': 'wages', '生命力': 'vitality', '救生场所': 'rescue stations', '房屋': 'houses',
  '利息': 'interest', '经营求财': 'business pursuits', '活物': 'living things', '生生不息': 'endless renewal',
  '诞生': 'birth', '生日': 'birthdays', '生存': 'survival', '种植': 'planting', '制造': 'manufacturing',
  '制作': 'making', '鲜活物': 'fresh living things', '一切生活状态好的动植物': 'thriving flora & fauna',
  '生活所需的必需品': 'daily necessities', '吃喝': 'food & drink', '住房': 'housing', '工厂': 'factories',
  '车间': 'workshops', '车床': 'lathes', '生产部门': 'production departments', '交易所': 'exchanges',
  '商超': 'supermarkets', '市场': 'markets', '旺于季夏土': 'prospers in late-summer Earth',
  '相于夏火': 'assisted in summer Fire', '休于秋金': 'rests in autumn Metal', '囚于冬水': 'trapped in winter Water',
  '死于春木': 'dies in spring Wood', '住房建筑': 'housing & construction', '经商求财': 'commerce & wealth',
  '财运财星': 'wealth fortune & star', '生意成败': 'business success or failure', '国际货币': 'international currency',
  '钱财利润': 'money & profit', '经济效益': 'economic returns', '企业生产': 'enterprise production',
  '产品质量': 'product quality', '生长生存': 'growth & survival',
  '生门宜求财赴任建筑婚姻添丁': 'Life Gate favours wealth, office, building, marriage & children',
  '代表学文科学生': 'represents humanities students', '连绵': 'continuous', '延续': 'continuation',
  '不断': 'unceasing', '看待事物的眼光是连续变化的': 'sees things as continuously evolving',
  '脾胃不调': 'spleen-stomach imbalance', '富翁': 'the wealthy', '房产商': 'property developers',
  '创业者': 'entrepreneurs', '投资人': 'investors', '生意人': 'businesspeople', '包工头': 'contractors',
  '生产劳动者': 'production workers', '企业管理者': 'enterprise managers', '从事金融机构者': 'finance workers',
  '资本投资者': 'capital investors', '经济有关公务员': 'economic officials', '土地部门': 'land departments',
  '金融部门': 'finance departments', '经营部门': 'business departments', '经商人员': 'merchants',
  '养殖业工人': 'husbandry workers', '乐观向上': 'optimistic', '生长的土地': 'fertile land',
  '活着的人': 'the living', '起死回生': 'back from the brink', '勤劳务实': 'diligent & practical',
  '善于经营': 'good at business', '财运好': 'good wealth luck', '脚踏实地': 'down-to-earth',
  '乐观积极': 'positive & upbeat', '生机勃勃': 'brimming with life', '诚恳乐观': 'sincere & optimistic',
  '活泼稳重': 'lively yet steady', '有经济头脑': 'business-minded', '商场': 'malls', '山坡': 'hillsides',
  '超市': 'supermarkets', '交易市场': 'trading markets', '生活场所': 'living spaces',
  '房屋土地': 'houses & land', '工厂生产基地': 'factory bases', '农场生产基地': 'farm bases',
  '证券银行场所': 'securities & banking venues', '商品交易场所': 'trading venues', '销售部': 'sales departments',
  '妇女产育院': 'maternity hospitals', '创业': 'starting ventures', '置办产业': 'acquiring property',
  '置业': 'property buying', '求嗣': 'praying for heirs', '贸易': 'trade', '上官': 'taking office',
  '牧养': 'herding', '祭奠': 'memorial rites', '埋葬治丧': 'burial & mourning',
  '生门+天蓬有财但来路不正': 'Life Gate + Tianpeng: wealth from dubious sources',
  '乾金之卦': 'trigram of Qian Metal', '性刚而好斗': 'hard and combative',
  '所主名正言顺之事': 'governs legitimate matters', '至极之神': 'deity of the utmost',
  '万物之父': 'father of all things', '扬之神': 'deity of display', '威悍之神': 'deity of might',
  '利扬兵布阵行军出兵': 'favours deploying troops', '乾金宫威严之神': 'stern deity of the Qian palace',
  '刚健好动': 'vigorous & active', '形圆其质坚': 'round in form, firm in substance',
  '可以扬兵征战': 'fit for military campaigns', '扬兵布阵': 'troop deployment', '行军打仗': 'marching to war',
  '乘飞机出行': 'air travel', '高大': 'tall & grand', '天空': 'the sky', '虚无': 'emptiness',
  '极端': 'extremes', '重要': 'important', '主宰': 'dominion', '意志': 'will', '灵魂': 'soul',
  '自然': 'nature', '恩赐': 'blessings', '幸福': 'happiness', '谋望': 'aspirations', '博奕': 'gaming',
  '不切实际': 'unrealistic', '理想': 'ideals', '思想境界高': 'lofty mindset', '活泼可爱': 'lively & charming',
  '宇宙': 'the cosmos', '天涯海角': 'the ends of the earth', '跳跃的动作': 'leaping motions',
  '理想高远': 'lofty ideals', '新颖': 'novel', '张扬': 'flamboyant', '公开': 'public', '宏大': 'grand',
  '壮志凌云': 'soaring ambition', '风云激荡': 'stirring times', '高谈阔论': 'grand talk', '吹牛': 'boasting',
  '情怀': 'sentiment', '变动不居': 'ever-changing', '求新求变': 'seeking novelty & change',
  '长者': 'elders', '航天员': 'astronauts', '志向远大之人': 'the highly ambitious', '首脑': 'heads of state',
  '君父': 'sovereign & father', '神甫': 'priests', '牧师': 'pastors', '有威望之人': 'the prestigious',
  '老人': 'the elderly', '刚健的男人': 'vigorous men', '空姐': 'flight attendants', '魁梧': 'burly',
  '脸方正': 'square face', '手绵软': 'soft hands', '言语掷地有声': 'weighty words',
  '刚健有力': 'strong & forceful', '志向高远': 'high aspirations', '勇猛果敢': 'brave & resolute',
  '不怒而威': 'commanding without anger', '刚强好动': 'tough & restless', '有时好高骛远': 'sometimes overreaching',
  '骨肋': 'ribs', '屁股': 'buttocks', '上焦': 'upper burner', '晴空万里': 'cloudless skies',
  '高空天际': 'high heavens', '烈日当空': 'sun at zenith', '蓝天': 'blue sky', '楼顶': 'rooftops',
  '飞机场': 'airports', '开阔高地': 'open highlands', '高楼大厦': 'skyscrapers', '天井': 'skylight courts',
  '天车': 'overhead cranes', '开阔地': 'open ground', '高空': 'high altitude', '经理室': 'manager’s office',
  '豪华地方': 'luxurious places', '楼房最高层': 'top floors', '旗帜': 'flags', '高大之物': 'tall things',
  '向上之物': 'upward things', '金玉': 'gold & jade', '宝石': 'gems', '剑戟': 'swords & halberds',
  '刀枪': 'blades & guns', '高档': 'high-grade', '钱': 'money', '铜铁': 'copper & iron',
  '光亮玲珑物': 'bright delicate things', '旋转活动物': 'rotating things', '直升飞机': 'helicopters',
  '风车': 'windmills', '贝壳': 'shells', '飞鸟': 'flying birds', '航天': 'spaceflight', '航空': 'aviation',
  '航线': 'flight routes', '高大的树': 'tall trees', '农作物': 'crops', '高山或高原植物': 'alpine plants',
  '圆形的水果': 'round fruits', '出击进攻': 'attacking', '上升飞腾': 'soaring rise', '举事': 'launching ventures',
  '向外拓展': 'outward expansion', '宜攻不宜守': 'favours attack over defence', '宜动不宜静': 'favours motion over rest',
  '主积极向上远大前程': 'augurs bright prospects', '利出击举事升迁': 'good for action, ventures & promotion',
  '备注': 'note', '若遇到丁': 'if Ding is met', '牛皮吹上天': 'boasts to the sky', '赤白': 'crimson-white',
  '孕育': 'gestation', '酝酿': 'brewing', '尚未成形': 'not yet formed', '潜在可能': 'latent potential',
  '大红': 'bright red', '亮红': 'vivid red', '赤': 'crimson', '大': 'large', '圆': 'round',
  '片状': 'flake-shaped', '伤加庚加白虎多主交通事故': 'Harm + Geng + White Tiger augurs traffic accidents',
  '外科手术医生': 'surgeons', '手术室': 'operating theatres', '公安局': 'police bureaus',
  '出行赶路': 'urgent travel', '伤门+天冲快速行动征伐有力': 'Harm Gate + Tianchong: swift forceful action',
  '伤门+天内大凶(因伤致病)': 'Harm Gate + Tianrui: very bad (injury becomes illness)',
  '光明正大': 'open & aboveboard', '粉': 'pink', '浅白': 'pale white', '白银': 'silver',
  '致密': 'dense', '精': 'refined', '错误': 'mistakes', '叛逆': 'rebellion', '创新': 'innovation',
  '变革': 'reform', '更新': 'renewal', '万物初新皆收成': 'renewal ripens into harvest', '金味辛': 'Metal tastes pungent',
  '物成而后有味': 'flavour follows completion', '试错': 'trial & error', '金钱剑原理': 'coin-sword principle',
  '疙瘩': 'lumps', '瘤': 'tumours', '骨刺': 'bone spurs', '湿疹': 'eczema', '粉刺': 'acne', '痘': 'pimples',
  '呼吸道': 'airways', '喉咙': 'throat', '鼻腔': 'nasal cavity', '胸腔': 'chest cavity', '股': 'thighs',
  '温润细腻': 'warm & delicate', '外柔内刚': 'soft outside, firm inside', '镇静': 'calm', '通达': 'astute',
  '柔润': 'supple', '灵动': 'nimble', '忠诚爽朗': 'loyal & hearty', '温润秀气': 'gentle & refined',
  '自尊但虚荣': 'proud but vain', '意志稍不坚': 'slightly weak-willed', '洁身自好': 'self-respecting',
  '敏感': 'sensitive', '爱面子': 'face-saving', '内敛挑战旧权威': 'quietly challenges old authority',
  '指出要害': 'pinpoints the crux', '不服管教': 'unruly', '不安分': 'restless', '没事找事': 'stirs up trouble',
  '修长方正': 'slender & square', '皮肤嫩白': 'fair skin', '脸长凹腮': 'long face, hollow cheeks',
  '得令时是良好的材料': 'fine material in season', '失令时变成瓦砾': 'rubble out of season',
  '秋霜': 'autumn frost', '露珠': 'dewdrops', '冰霜': 'ice & frost', '月': 'the moon',
  '珠宝店': 'jewellery shops', '首饰加工厂': 'jewellery workshops', '石块': 'stones',
  '五金加工场': 'hardware workshops', '手表厂': 'watch factories', '工艺品厂': 'craft factories',
  '罪人': 'offenders', '犯法者': 'lawbreakers', '革命者': 'revolutionaries', '改革之人': 'reformers',
  '宗教徒': 'religious believers', '珠宝商': 'jewellers', '金融家': 'financiers', '科学狂人': 'mad scientists',
  '检查监督者': 'inspectors', '纠错改革者': 'correctors & reformers',
  '寄在人或动物身上的生物或病': 'parasites or diseases on hosts', '虫卵': 'insect eggs',
  '动物的卵或胎坯': 'animal eggs or embryos', '白鸽': 'white doves', '小型鸟类': 'small birds',
  '颗粒状粮食': 'grain kernels', '大豆': 'soybeans', '玉米': 'corn', '小型花朵': 'small blossoms',
  '茉莉': 'jasmine', '米兰': 'milan flowers', '花果': 'flowers & fruit', '蒜': 'garlic', '姜': 'ginger',
  '辛辣植物': 'pungent plants', '花蕊': 'stamens', '小型花卉': 'small flowers',
});

/* Batch 3 — remaining symbol blocks. */
Object.assign(window.QMS_TERMS_EN, {
  '饰品': 'ornaments', '细软首饰': 'fine jewellery', '戒指': 'rings', '项链': 'necklaces',
  '手镯': 'bracelets', '小摆件': 'small ornaments', '螺丝': 'screws', '佛珠': 'prayer beads',
  '手表': 'watches', '金银珠宝': 'gold, silver & jewels', '小刀': 'small knives', '保险柜': 'safes',
  '骸骨': 'skeletal remains', '工程塑料': 'engineering plastics', '金子': 'gold', '玉器': 'jade ware',
  '金饰品': 'gold ornaments', '晶体': 'crystals', '针': 'needles', '剪刀': 'scissors', '笔': 'pens',
  '药片': 'tablets', '药丸': 'pills', '精致小食': 'dainty snacks', '颗粒类': 'granular things',
  '毁折之星': 'star of ruin', '破财伤人': 'lost wealth & injury', '临九天破敌': 'routs foes via Nine Heaven',
  '金秋肃杀': 'stern autumn air', '喜欢收割': 'fond of reaping', '斗争': 'struggle', '柱状物': 'columnar things',
  '大凶(毁折之星)': 'very inauspicious (star of ruin)', '浅红': 'pale red', '右肋': 'right ribs',
  '牙痛': 'toothache', '咽炎': 'pharyngitis', '呼吸道疾病': 'respiratory illness',
  '口舌之人': 'gossipmongers', '毁谤者': 'slanderers', '破坏者': 'destroyers', '讼师': 'litigators',
  '算命先生': 'fortune-tellers', '好搬弄是非': 'stirs up gossip', '喜怒无常': 'moody',
  '破坏力强': 'highly destructive', '表达力出众': 'outstanding expression', '社交能力强': 'socially adept',
  '凉风': 'cool winds', '秋天肃杀之气': 'austere autumn air', '话筒': 'microphones',
  '废旧物品': 'scrap goods', '刀剪利器': 'blades & shears', '茶馆': 'teahouses',
  '律师事务所': 'law firms', '破旧建筑': 'dilapidated buildings', '口岸': 'ports of entry',
  '口舌争端': 'verbal disputes', '破坏拆除': 'demolition', '歌唱': 'singing', '占卜': 'divination',
  '拆除': 'tearing down', '练习口才': 'practising oratory', '不利于出战交兵': 'bad for battle',
  '可以养兵': 'good for training troops', '不利于经商': 'bad for commerce', '容易破财伤人': 'risks loss & injury',
  '宜加固营垒': 'fortify the camp', '屯兵固守': 'garrison & hold', '明朝于谦': 'Yu Qian of the Ming',
  '柱石': 'pillars', '脊梁': 'backbone', '反调': 'contrarian notes', '折腾': 'churn',
  '独特': 'unique', '小众': 'niche', '冷酷': 'cold', '独当一面': 'holds the fort alone',
  '力挽狂澜': 'stems the tide', '特立独行': 'maverick', '一意孤行': 'headstrong', '霸占主动': 'seizes initiative',
  '孤胆英雄': 'lone hero', '把坏事变好': 'turns bad to good', '恶变成善': 'evil turned good',
  '震慑力': 'deterrence', '感召力': 'charisma', '口才': 'eloquence', '重用口才': 'relies on eloquence',
  '先破后立': 'destroy then establish', '发扬破坏': 'wields destruction', '惩罚': 'punishment',
  '惩恶扬善': 'punishing evil, exalting good', '销售': 'sales', '军事': 'military affairs',
  '重工业': 'heavy industry', '机械维修': 'machine repair', '发声物': 'sound-making things',
  '发声钟表': 'chiming clocks', '公鸡': 'roosters', '画眉': 'thrushes', '钢管': 'steel pipes',
  '水泥管': 'cement pipes', '高塔': 'towers', '木棒': 'wooden rods', '筷子': 'chopsticks',
  '腰椎': 'lumbar spine', '中平偏凶(闭塞之门)': 'neutral-poor (gate of blockage)', '东南方': 'southeast',
  '巽木宫': 'Xun Wood palace', '阻塞': 'obstruction', '受阻': 'blocked', '不通': 'impassable',
  '有阻力': 'meets resistance', '躲藏之地': 'hiding places', '纪检部门': 'discipline inspection',
  '安全部门': 'security departments', '防洪抢险': 'flood control', '学习理工科': 'STEM study',
  '武官': 'military officers', '军队': 'the army', '技术': 'technology', '堵塞': 'clogging',
  '杜绝': 'shutting out', '检察': 'procuratorial work', '躲藏': 'hiding', '胸罩': 'bras',
  '避孕套': 'condoms', '宅男': 'homebodies', '专利': 'patents', '精密技术': 'precision technology',
  '夜行动物': 'nocturnal animals', '躲藏动物': 'hiding animals', '商标': 'trademarks', '贞洁': 'chastity',
  '防御部队': 'defence troops', '盾牌': 'shields', '盔甲': 'armour', '手套': 'gloves',
  '上锁阻挡和隔离': 'locking, blocking & isolation', '排他性': 'exclusivity', '不能共享的': 'unshareable',
  '隐藏性的秘密': 'hidden secrets', '用杜门可以防小人暗算': 'Block Gate wards off backstabbers',
  '理工技术范': 'tech-minded type', '阻止': 'stopping', '困难': 'difficulty', '限制': 'restriction',
  '闭塞不通': 'sealed off', '断绝': 'severance', '覆盖': 'covering', '遮掩': 'concealing',
  '关闭': 'closing', '艺技': 'arts & crafts', '花卉': 'flowers', '技术成果': 'technical achievements',
  '技术性强职业': 'technical professions', '科技技术执法机关': 'tech enforcement agencies',
  '保密躲藏方向隐藏部位秘密行事': 'secrecy, hiding & covert action', '行动受阻': 'action obstructed',
  '心血管堵塞血液不通畅': 'cardiovascular blockage', '躲灾避难防洪筑堤修筑城墙': 'sheltering, dyking & walling',
  '拥堵': 'congestion', '不明': 'unclear', '深绿': 'deep green', '食道': 'oesophagus',
  '郁结': 'stagnation', '抑郁症': 'depression', '气滞': 'qi stagnation', '便秘': 'constipation',
  '呼吸不畅': 'laboured breathing', '逃犯': 'fugitives', '躲避者': 'evaders', '密探': 'undercover agents',
  '特工': 'secret agents', '保密人员': 'classified staff', '技术人员': 'technicians',
  '科研人员': 'researchers', '理论工作者': 'theorists', '心理学者': 'psychologists',
  '武术散打': 'martial sparring', '佛教徒': 'Buddhists', '宗教信徒': 'believers', '神职工作': 'clergy work',
  '气功师': 'qigong masters', '隐遁修仙': 'reclusive cultivation', '公检法': 'justice organs',
  '安全保密人员': 'security staff', '聋哑人': 'the deaf-mute', '中风者': 'stroke patients',
  '仓储保管人员': 'warehouse keepers', '理论家': 'theoreticians', '气功': 'qigong',
  '技术管理人员': 'technical managers', '公检法制法机关': 'law-and-justice agencies',
  '保密安全等部门': 'security & secrecy departments', '晦涩': 'obscure', '呆滞': 'dull',
  '深色安然': 'dark and quiet', '体会到的': 'the felt', '感觉到的': 'the sensed', '意识到的': 'the realised',
  '想象到的': 'the imagined', '内向封闭': 'closed-in', '不善交际': 'unsociable', '善于隐藏': 'good at hiding',
  '沉默': 'silent', '闭塞不爱言语': 'taciturn', '心平气和': 'even-tempered', '杜绝限制': 'shut-out limits',
  '行事秘密': 'acts in secret', '密室': 'secret rooms', '隐蔽处': 'hideouts', '防空洞': 'air-raid shelters',
  '深山': 'deep mountains', '封闭空间': 'enclosed spaces', '实验室': 'laboratories',
  '保密机构': 'classified agencies', '隔离带': 'isolation strips', '绿篱': 'hedges', '通道': 'passages',
  '闸口': 'sluice gates', '门槛': 'thresholds', '闭塞之地': 'sealed-off places',
  '交通拥堵之地': 'congested places', '躲避隐藏': 'evading & hiding', '防守': 'defence',
  '科研': 'research', '技术开发': 'tech development', '避难': 'refuge', '避祸': 'dodging misfortune',
  '藏形': 'concealing form', '躲灾避难': 'sheltering from calamity', '捕盗剿贼': 'suppressing bandits',
  '防洪筑堤': 'flood dyking', '判决隐狱': 'sentencing & hidden prisons', '余事皆不利': 'all else unfavourable',
  '空气': 'air', '气流': 'air currents', '气旋': 'cyclones', '杜门+天蓬凶(隐匿犯罪)': 'Block Gate + Tianpeng: bad (hidden crime)',
  '杜门+天英中平(怀才不遇)': 'Block Gate + Tianying: neutral (unrecognised talent)',
  '六丁六甲之阴神': 'yin deity of the Six Ding & Six Jia', '神之最灵者': 'most uncanny of deities',
  '虚诈虚耗之神': 'deity of deceit & drain', '有纠缠力量': 'entangling power', '怪异的现象': 'strange phenomena',
  '形虚幻': 'illusory form', '怪异': 'strangeness', '虚幻': 'illusion', '梦境': 'dreamscapes',
  '火光': 'firelight', '变来变去': 'ever-shifting', '反反复复': 'back-and-forth', '虚诈': 'deceit',
  '虚伪': 'hypocrisy', '华而不实': 'flashy but hollow', '闪烁不定': 'flickering', '光怪陆离': 'phantasmagoric',
  '耀眼': 'dazzling', '猜疑': 'suspicion', '狠毒': 'vicious', '纠缠': 'entanglement',
  '拐弯抹角': 'roundabout', '心性不定': 'unsettled mind', '惊疑扰乱': 'alarm & confusion',
  '花里胡哨': 'gaudy', '眼花缭乱': 'dizzying', '牵连': 'implication', '罗网': 'nets & snares',
  '牵缠': 'entanglement', '妖魔鬼魅': 'demons & phantoms', '虚幻不实': 'unreal', '心惊肉跳': 'heart-pounding dread',
  '捆绑': 'binding', '足智多谋': 'resourceful', '灵异': 'the uncanny', '感情不稳定': 'unstable feelings',
  '疾病反复': 'relapsing illness', '小事反复折腾': 'small matters churn endlessly', '情感乱心智': 'feelings cloud judgement',
  '静观其变': 'watch and wait', '虚伪之人': 'hypocrites', '心机深沉者': 'the deeply scheming',
  '惊恐之人': 'the frightened', '怪异之人': 'odd people', '梦魇者': 'nightmare sufferers',
  '委屈婉转之人': 'the meekly aggrieved', '狡猾之人': 'the cunning', '善变之人': 'the fickle',
  '虚诈之人': 'the deceitful', '变化无常之人': 'the capricious', '死缠烂打之人': 'relentless pesterers',
  '漂亮妖艳之人': 'the bewitching', '口舌毒辣之人': 'the sharp-tongued', '呻吟之人': 'groaners',
  '疑心之人': 'the suspicious', '做梦人': 'dreamers', '精神病患者': 'the mentally ill',
  '对神秘文化感兴趣者': 'occult enthusiasts', '信佛信道者': 'Buddhist & Daoist believers', '公吏': 'clerks',
  '牙婆': 'matchmakers', '水蛇腰': 'willowy waist', '驼背': 'hunchbacked', '头发黄或稀少': 'sparse yellowish hair',
  '大脑门': 'broad forehead', '身材苗条': 'slender build', '多疑善变': 'suspicious & fickle',
  '狡猾虚伪': 'sly & false', '惊恐不安': 'frightened & uneasy', '缠绕纠缠': 'twining entanglement',
  '表里不一': 'two-faced', '虚伪巧诈': 'false & crafty', '奸佞心毒': 'treacherous & venomous',
  '心口不一': 'says one thing, means another', '精神': 'spirit', '精神类': 'psychiatric',
  '噩梦失眠': 'nightmares & insomnia', '惊悸': 'palpitations', '怪病缠绵难愈': 'lingering strange illness',
  '怪异天象': 'strange skies', '雾霾浓烟': 'smog & smoke', '弯曲小道': 'winding paths',
  '阴森之地': 'eerie places', '火灾现场': 'fire scenes', '弯路': 'detours', '海岸线': 'coastlines',
  '塔吊': 'tower cranes', '高压线': 'power lines', '山脉': 'mountain ranges', '弯曲的建筑物': 'curved buildings',
  '长城': 'the Great Wall', '反光的建筑物': 'reflective buildings', '丝线': 'silk threads',
  '缠绕之物': 'twining things', '蛇形物': 'serpentine things', '弯曲之物': 'curved things',
  '绳带': 'cords & straps', '锁链': 'chains', '香火': 'incense fires', '带花纹的布和衣服': 'patterned cloth & clothes',
  '渔网': 'fishing nets', '鞋带': 'shoelaces', '领带': 'neckties', '手链': 'chain bracelets',
  '表链': 'watch chains', '拉锁': 'zips', '发辫': 'braids', '弯曲的东西': 'curved things',
  '徘徊的东西': 'lingering things', '网状的衣服': 'mesh clothing', '网络': 'networks', '彩绘': 'painted patterns',
  '线': 'threads', '一切细长物品': 'all slender things', '蟒': 'pythons', '爬虫类': 'reptiles',
  '蜈蚣': 'centipedes', '海参': 'sea cucumbers', '海肠': 'sea worms', '地蚕': 'ground grubs',
  '龙抓槐': 'twisted locust trees', '爬山虎': 'ivy', '西瓜秧': 'melon vines', '南瓜秧': 'pumpkin vines',
  '黄瓜秧': 'cucumber vines', '豆角秧': 'bean vines', '牵牛': 'morning glory', '红薯秧': 'sweet-potato vines',
  '藤萝': 'wisteria vines', '紫藤': 'wisteria', '一切蔓状类植物': 'all trailing plants',
  '虚惊一场': 'a false alarm', '怪梦': 'strange dreams', '纠缠不清': 'hopeless entanglement',
  '变幻莫测': 'unfathomable change', '惊吓': 'frights', '意外': 'accidents', '主虚惊怪异': 'augurs scares & oddities',
  '牵扯纠缠不清': 'tangled implications', '事多反复变化': 'matters keep shifting', '梦寐不安': 'restless sleep',
  '杂色': 'motley colours', '中央（寄坤宫）': 'center (lodged in Kun)', '中央（寄西南）': 'center (lodged southwest)',
  '四季长夏': 'late summer of all seasons', '厚实': 'thick & solid', '敦实': 'stocky', '财富': 'wealth',
  '中正': 'centred & upright', '厚德载物': 'great virtue carries all', '资本': 'capital', '宽厚': 'magnanimous',
  '资产': 'assets', '多肉': 'fleshy', '收容式积聚': 'gathering accumulation', '忠诚': 'loyal',
  '直方大': 'straight, square, great', '排斥分发': 'resists dispersal', '抽象也是收容': 'abstractly, containment',
  '抽象也是资本': 'abstractly, capital', '胸': 'chest', '乳房': 'breasts', '臀部': 'buttocks',
  '肋骨': 'ribs', '背部': 'the back', '忠厚': 'honest & kind', '老成': 'seasoned', '生硬': 'stiff',
  '果敢豪杰': 'bold heroes', '憨厚': 'simple & honest', '愚笨': 'slow-witted', '行动迟缓': 'slow-moving',
  '诚实': 'honest', '大度': 'magnanimous', '踏实': 'grounded', '形体敦厚': 'stout build',
  '四方脸': 'square face', '肤黄白': 'sallow-fair skin', '身体多肉': 'fleshy body',
  '得令时豪放果敢': 'bold & decisive in season', '失令时发呆': 'dazed out of season', '星云': 'nebulae',
  '银河': 'the Milky Way', '云彩': 'clouds', '霞': 'rosy mist', '黄沙': 'yellow sands', '古城': 'old towns',
  '起居室': 'living rooms', '墙壁': 'walls', '水泥横梁': 'concrete beams', '堤防': 'embankments',
  '坟地': 'burial grounds', '陵园': 'cemeteries', '中介所': 'agencies', '顾问机构': 'consultancies',
  '水泥厂': 'cement plants', '大山': 'great mountains', '停车场': 'car parks', '建筑物': 'buildings',
  '丞相': 'chancellors', '后勤人员': 'logistics staff', '会计': 'accountants', '金融机构': 'financial institutions',
  '出纳': 'cashiers', '银行职员': 'bank clerks', '中介人': 'middlemen', '矿山开采者': 'miners',
  '从农者': 'farm workers', '德高望重之人': 'the venerable', '宽厚中庸之人': 'the magnanimous & moderate',
  '骆驼': 'camels', '企鹅': 'penguins', '叶子宽厚或土生肉质果实': 'broad-leaved or earthy fleshy fruits',
  '芭蕉': 'plantains', '倭瓜': 'squash', '白薯': 'sweet potatoes', '山药': 'yams', '萝卜': 'radishes',
  '根茎类': 'root vegetables', '番薯': 'sweet potatoes', '能装藏的容器': 'containers that hold & store',
  '陶制品': 'earthenware', '土制品': 'clay goods', '瓷碗': 'porcelain bowls', '瓷杯': 'porcelain cups',
  '瓷勺': 'porcelain spoons', '瓷盆': 'porcelain basins', '瓷缸': 'porcelain jars', '水泥制品': 'cement goods',
  '城池': 'walled cities', '涂料': 'coatings', '收藏品': 'collectibles', '凸起物': 'protrusions',
  '纸币': 'banknotes', '钱包': 'wallets', '存钱罐': 'piggy banks', '肉排': 'meat cutlets',
  '石碑': 'stone steles', '巨石': 'boulders', '厚实食品': 'hearty foods', '面食': 'wheaten foods',
  '鸡排': 'chicken cutlets', '牛排': 'steaks', '羊排': 'lamb chops', '沉重': 'heavy',
  '文昌之星': 'star of scholarship', '大学': 'universities', '文教': 'culture & education',
  '服装': 'clothing', '时尚': 'fashion', '大吉(文昌之星)': 'very auspicious (scholarship star)',
  '绿': 'green', '翠': 'emerald', '风疾': 'wind ailments', '感冒': 'colds', '股部疾病': 'thigh ailments',
  '肠道疾病': 'bowel ailments', '考生': 'exam candidates', '文官': 'civil officials', '顾问': 'advisers',
  '参谋': 'staff officers', '文秘': 'secretaries', '温文尔雅': 'cultured & gentle', '博学多才': 'erudite',
  '聪明灵秀': 'bright & graceful', '善良仁慈': 'kind & benevolent', '谦虚有礼': 'modest & courteous',
  '和风细雨': 'gentle breeze & drizzle', '微风': 'breezes', '花开叶茂': 'blooming & leafy',
  '文房四宝': 'the four scholar’s treasures', '经书': 'scriptures', '教材': 'textbooks',
  '绳线': 'cords & threads', '丝绸': 'silk', '香': 'incense', '道观': 'Daoist temples', '书房': 'studies',
  '文化场所': 'cultural venues', '考场': 'exam halls', '读书求学': 'study & schooling', '求师': 'seeking teachers',
  '拜佛祈福': 'worship & blessing', '教学': 'teaching', '设计策划': 'design & planning', '求学': 'pursuing study',
  '拜师': 'apprenticeship', '婚嫁': 'weddings', '祈福': 'praying for blessings', '见贵人': 'meeting benefactors',
  '文书契约': 'documents & contracts', '读书学习好时机': 'a fine time for study', '利于升学': 'good for advancement',
  '教化': 'edification', '师相': 'teacher-minister', '辅佐': 'assisting', '指导': 'guidance',
  '奉献': 'devotion', '温雅': 'gentle elegance', '学习': 'learning', '传播': 'dissemination',
  '客观的自媒体': 'objective self-media', '说话礼貌': 'polite speech', '传染': 'contagion',
  '有教养': 'well-bred', '彬彬有礼': 'courteous', '含蓄稳重': 'reserved & steady', '谦恭节制': 'humble & temperate',
  '同情包容': 'sympathetic & tolerant', '柔和温存': 'gentle & tender', '大善人': 'great philanthropists',
  '利他主义': 'altruism', '辅佐别人': 'assisting others', '教授指导': 'teaching & guidance', '设计': 'design',
  '规划': 'planning', '工艺': 'craftsmanship', '技术支持': 'technical support', '抛砖引玉': 'a humble lead-in',
  '辅助物': 'auxiliary items', '保护物': 'protective items', '羽绒': 'down feathers', '护甲': 'armour',
  '家具': 'furniture', '桌椅': 'tables & chairs', '空调': 'air conditioners', '风扇': 'fans',
  '窗口': 'windows', '沟通物': 'communication tools', '谋划物': 'planning tools', '电线': 'electric wires',
  '绳子': 'ropes', '栅栏': 'fences', '弯曲物': 'curved things', '小花草': 'small flowers & grasses',
  '丝瓜': 'loofahs', '泥鳅': 'loaches', '带鱼': 'ribbonfish', '吉(三吉门之一)': 'auspicious (one of the three lucky gates)',
  '从容': 'unhurried', '休闲': 'leisure', '休养生息': 'rest & recuperation', '政府': 'government',
  '一家人': 'family', '休息冬眠': 'rest & hibernation', '长时间不动的': 'long-still things',
  '退休之人': 'retirees', '谒贵': 'calling on the noble', '油盐酱醋': 'kitchen staples', '水产': 'aquatic products',
  '流动性强': 'highly fluid', '一切流动性质的事物': 'all fluid things', '一切液体': 'all liquids',
  '能动的家电': 'moving appliances', '含水多的果蔬': 'watery produce', '水中动物': 'aquatic animals',
  '水牛': 'water buffalo', '旺于冬水': 'prospers in winter Water', '相于秋金': 'assisted in autumn Metal',
  '休于春木': 'rests in spring Wood', '囚于夏火': 'trapped in summer Fire', '死于季夏土': 'dies in late-summer Earth',
  '休闲旅游': 'leisure travel', '接待': 'reception', '懒散': 'indolent', '休息': 'rest',
  '漫不经心': 'nonchalant', '调养': 'recuperation', '调理整理': 'tending & ordering', '美体': 'body care',
  '化妆': 'makeup', '美发': 'hairdressing', '娱乐': 'entertainment', '暴露': 'exposure',
  '跟水有关系': 'water-related', '退休': 'retirement', '幕贵': 'patrons behind the curtain',
  '老领导': 'old superiors', '幕后有一定人脉关系': 'backstage connections', '帘幕贵人': 'hidden benefactors',
  '萎靡': 'listless', '颓废': 'decadent', '将就': 'making do', '凑合': 'getting by', '应付': 'coping',
  '暗箱操作': 'backroom dealing', '最好的恋情': 'the best of romances', '不折腾': 'no churn',
  '不干涉': 'no meddling', '不猜忌': 'no jealousy', '不怀疑': 'no doubting', '互相呵护': 'mutual care',
  '温润如玉': 'warm as jade', '泌尿': 'urinary', '肾虚': 'kidney deficiency', '耳疾': 'ear ailments',
  '休闲者': 'leisure-seekers', '旅行者': 'travellers', '外交官': 'diplomats', '中间人': 'go-betweens',
  '退休者': 'the retired', '品质高贵之人': 'people of noble character', '旅游有关的人': 'tourism people',
  '修剪理发': 'trimming & barbering', '修理工': 'repairmen', '营养师': 'dietitians', '护理人员': 'care staff',
  '离退休人员': 'retirees', '疗养之人': 'convalescents', '清闲之人': 'the idle', '懒散之人': 'the indolent',
  '睡觉者': 'sleepers', '接待员': 'receptionists', '美容美体': 'beauty & body care', '美容美发': 'beauty & hair',
  '白领人士': 'white-collar workers', '医护人员': 'medical staff', '旅游业人': 'tourism workers',
  '美丽漂亮': 'beautiful', '气质较好': 'fine bearing', '生活比较轻松': 'easy-going life', '语音偏低': 'low voice',
  '语速偏慢': 'slow speech', '着装宽松': 'loose dress', '休闲娱乐': 'leisure & fun',
  '半睁着眼的人': 'heavy-lidded people', '不慌不忙': 'unhurried', '安静状态': 'quiet states', '温和': 'mild',
  '灵活善变': 'flexible & adaptive', '善于交际': 'sociable', '圆滑': 'smooth', '善把握时机': 'seizes the moment',
  '休闲安定': 'leisurely & settled', '安然模样': 'serene look', '懒散倦怠': 'languid', '性情温顺': 'docile',
  '没有活力': 'listless', '旺者喜爱干净': 'the thriving love cleanliness', '行事井井有条': 'methodical',
  '休神养性': 'resting spirit, nurturing nature', '休闲场所': 'leisure venues', '宾馆': 'hotels',
  '旅社': 'inns', '茶室': 'tearooms', '大海': 'the sea', '流动水景': 'flowing waterscapes',
  '江河湖泊': 'rivers & lakes', '湖光山色': 'lakes & hills', '海滨等有水的场所': 'seaside watery places',
  '卧室': 'bedrooms', '疗养院': 'sanatoria', '娱乐厅': 'entertainment halls', '外交公关': 'diplomacy & PR',
  '求见贵人': 'seeking audience with benefactors', '休养': 'recuperation', '旅游': 'tourism', '求职': 'job-seeking',
  '谒见领导': 'calling on leaders', '见贵': 'meeting the noble', '一切谋事': 'all undertakings', '迁徙': 'migration',
  '断狱': 'judging cases', '断官司': 'settling lawsuits', '冬天': 'winter', '星期天': 'Sundays',
  '节假日': 'holidays', '坤方之土神': 'earth deity of the Kun quarter', '主柔顺虚恭之事': 'governs docile humble matters',
  '坚牢稳固之神': 'deity of firmness', '隐晦之神': 'deity of obscurity', '利屯兵固守': 'good for garrisoning',
  '潜藏万物': 'harbours all things', '温顺安静': 'docile & quiet', '宽厚让人': 'generous & yielding',
  '形厚有柄': 'thick form with a handle', '利于屯兵固守': 'good for holding ground', '跟踪': 'tailing',
  '矮小': 'short', '稳定': 'stable', '厚重': 'weighty', '文静': 'quiet', '恭敬': 'respectful',
  '谦卑': 'humble', '消极': 'passive', '模糊': 'vague', '博大': 'vast', '关怀': 'caring',
  '缓慢': 'slow', '困惑': 'perplexity', '病患牢狱': 'illness & imprisonment', '暗昧哭泣': 'dim weeping',
  '死伤': 'death & injury', '顽固不化': 'incorrigible', '埋葬': 'burial', '囤积': 'hoarding',
  '播种': 'sowing', '农事活动': 'farm work', '压抑': 'repression', '母亲': 'mothers', '妻子': 'wives',
  '房地产从业者': 'real-estate workers', '守成之人': 'preservers of the status quo', '乡农': 'village farmers',
  '道姑': 'Daoist nuns', '村姑': 'village girls', '地下工作者': 'underground operatives',
  '不公开的职业': 'undisclosed professions', '吝啬之人': 'misers', '慢吞吞的人': 'dawdlers',
  '卜卦之人': 'diviners', '要饭的': 'beggars', '大腹': 'big-bellied', '肥厚': 'thick & fat',
  '方脸多肉': 'fleshy square face', '肥胖': 'obese', '身材五短': 'squat build', '声音如瓮': 'voice like a jar',
  '厚道宽容': 'kind & forgiving', '柔顺安静': 'docile & quiet', '包容隐忍': 'tolerant & forbearing',
  '踏实稳重': 'grounded & steady', '保守顺从': 'conservative & compliant', '吝啬节俭': 'stingy & frugal',
  '有时过于自私消极': 'sometimes too selfish & passive', '缺乏上进心': 'lacking ambition',
  '慢而稳重': 'slow but steady', '拿保温杯的老干部形象': 'the thermos-toting cadre type', '肉': 'flesh',
  '唇': 'lips', '臀': 'buttocks', '大地平原': 'great plains', '低洼地': 'low-lying land',
  '地窖': 'cellars', '矮房': 'low houses', '平地': 'flat ground', '乡村': 'villages', '地基': 'foundations',
  '低洼地带': 'lowlands', '阴暗的地下室': 'dark basements', '地道': 'tunnels', '地下铁': 'subways',
  '地摊': 'street stalls', '地炉': 'floor hearths', '地炕': 'heated floors', '地契': 'land deeds',
  '坛罐': 'jars & urns', '柔软之物': 'soft things', '沙石': 'sand & gravel', '缸': 'vats',
  '瓦盆': 'clay basins', '储存粮食的器皿': 'grain vessels', '储存衣物的柜子': 'clothes chests',
  '首饰盒': 'jewellery boxes', '载物载人的车子': 'carts for goods & people', '符箓': 'talismans',
  '药饵': 'medicinal baits', '子母牛': 'cow with calf', '虫类': 'insects',
  '大象等动作缓慢性情温柔的动物': 'slow gentle animals like elephants', '稻豆': 'rice & beans',
  '地衣': 'lichens', '地丁': 'violets', '荸荠': 'water chestnuts', '大蒜': 'garlic', '中草药': 'herbal medicine',
  '守旧不动': 'holding to the old', '隐藏蓄积': 'hidden accumulation', '藏匿收藏': 'stashing & collecting',
  '农耕': 'farming', '安营防守': 'encamping & defending', '宜守不宜攻': 'favours defence over attack',
  '宜静不宜动': 'favours stillness over motion', '主安稳固守': 'augurs steady holding',
  '利于防御': 'good for defence', '沐浴更衣': 'bathing & changing', '不稳定': 'unstable', '轻浮': 'frivolous',
});

/* Batch 4 — Life Gate combos, Harm/Block/View gates, Serpent, Tianxin, Tianzhu. */
Object.assign(window.QMS_TERMS_EN, {
  '流动': 'flow', '心思细密': 'meticulous mind', '装饰品': 'ornaments',
  '若坏事牵连日久遇生门则会继续牵连下去如慢性病': 'long-running troubles met by Life Gate drag on, like chronic illness',
  '消化系统(生门本身主生一般不论重病)': 'digestive system (Life Gate governs vitality, rarely grave illness)',
  '生门+天心大吉(大财贵人助力)': 'Life Gate + Tianxin: very auspicious (big wealth with backing)',
  '生门+天任吉(房产获利稳扎稳打)': 'Life Gate + Tianren: auspicious (steady property gains)',
  '生门+天内吉中带忧(赚钱辛苦)': 'Life Gate + Tianrui: good with worry (hard-earned money)',
  '凶(可为用)': 'inauspicious (usable)', '伤门又代表车辆也代表会驾驭车辆的人': 'Harm Gate also means vehicles and their drivers',
  '伤门两面性(本身坏了或抓坏的)': 'Harm Gate cuts both ways (broken, or catching the broken)',
  '伤门+天辅凶中带吉(得贵人指点)': 'Harm Gate + Tianfu: bad with good (a benefactor’s guidance)',
  '杜门+天辅中平(安心读书隐居)': 'Block Gate + Tianfu: neutral (quiet study & seclusion)',
  '休门+天心大吉(求官得官遇贵人)': 'Rest Gate + Tianxin: very auspicious (office gained, benefactor met)',
  '休门+天蓬外吉内凶(暗藏小人)': 'Rest Gate + Tianpeng: fair outside, foul inside (hidden schemers)',
  '休门+天辅文运亨通(利考试求学)': 'Rest Gate + Tianfu: scholarly fortune (good for exams & study)',
  '景门+天辅大吉(文运极佳考试必中)': 'View Gate + Tianfu: very auspicious (exam success assured)',
  '景门+天英中平偏凶(华而不实)': 'View Gate + Tianying: mediocre (flashy but hollow)',
  '景门+天心吉(有名望)': 'View Gate + Tianxin: auspicious (renown)',
  '景门+天内凶(文书出错惹祸)': 'View Gate + Tianrui: bad (paperwork errors bring trouble)',
  '开门+天心大吉中之大吉(官运亨通百事大吉)': 'Open Gate + Tianxin: supremely auspicious (career soars)',
  '开门+天冲吉(勇猛开拓)': 'Open Gate + Tianchong: auspicious (bold pioneering)',
  '开门+天蓬凶(防小人趁机)': 'Open Gate + Tianpeng: bad (beware opportunists)',
  '开门+天内不吉(开业遇阻)': 'Open Gate + Tianrui: unfavourable (openings obstructed)',
  '惊门+天柱大凶(口舌极重官司缠身)': 'Shock Gate + Tianzhu: very bad (heavy gossip & lawsuits)',
  '惊门+天心有惊无险(贵人化解)': 'Shock Gate + Tianxin: scare without harm (a benefactor resolves it)',
  '惊门+天内凶(因病受惊)': 'Shock Gate + Tianrui: bad (illness brings fright)',
  '死门+天内凶上加凶(重病不治)': 'Death Gate + Tianrui: doubly dire (grave untreatable illness)',
  '死门+天心凶中见吉(给绝症看病)': 'Death Gate + Tianxin: hope amid gloom (treating the incurable)',
  '死门+天蓬极凶(横死凶案)': 'Death Gate + Tianpeng: extremely dire (violent death)',
  '亮白': 'bright white', '亮黄': 'bright yellow', '棱角': 'edges & corners', '硬': 'hard',
  '暴力': 'violence', '魄力': 'boldness', '气概': 'mettle', '肃杀': 'austere severity',
  '凶恶': 'ferocious', '野蛮': 'savage', '技术过硬': 'rock-solid skills', '万物收敛有实': 'all things contract and ripen',
  '秋收而待来春': 'autumn harvest awaiting spring', '如果没有敌人就会窝里斗': 'without foes, fights within',
  '击刑时身心受重创': 'punishment strikes body and mind', '绝症': 'terminal illness', '骨钙': 'bone calcium',
  '嗓音': 'voice', '果决': 'resolute', '义薄云天': 'loyalty sky-high', '好战': 'warlike',
  '粗犷': 'rugged', '锐利': 'sharp', '刚强': 'unyielding', '威武': 'martial might',
  '刚健敏锐': 'vigorous & keen', '坚忍不拔': 'indomitable', '威严残暴': 'stern & brutal',
  '性刚质硬': 'hard of nature', '嫉恶如仇': 'hates evil like a foe', '勇猛': 'valiant',
  '不讲道理': 'unreasonable', '执拗': 'obstinate', '激动': 'agitated', '体型瘦长': 'lean & tall',
  '骨骼健壮': 'strong-boned', '长脸白皮肤': 'long fair face', '筋强骨健': 'strong sinews & bones',
  '得令时强硬': 'iron-hard in season', '失令时丧失威望': 'loses standing out of season', '雷霆': 'thunderbolts',
  '秋风': 'autumn winds', '关卡': 'checkpoints', '收费站': 'toll booths', '钢铁厂': 'steel mills',
  '机械厂': 'machine works', '铁路': 'railways', '兵器库': 'armouries', '金属加工厂': 'metalworks',
  '关隘': 'mountain passes', '武术家': 'martial artists', '本领高强之人': 'the highly skilled',
  '凶残之人': 'the cruel', '武断之人': 'the arbitrary', '屠户': 'butchers', '凶恶的动物': 'fierce animals',
  '毒蛇': 'venomous snakes', '生物病毒': 'viruses', '猿': 'apes', '果实坚硬之树': 'hard-fruited trees',
  '橡树': 'oaks', '核桃树': 'walnut trees', '石制品': 'stoneware', '石兽': 'stone beasts',
  '骨类': 'bones', '器械': 'apparatus', '金属制品': 'metal goods', '顽铁': 'crude iron',
  '硬金属': 'hard metals', '铁器': 'ironware', '利器': 'sharp implements', '五金': 'hardware',
  '钢材': 'steel', '矿物': 'minerals', '矿石': 'ores', '机器': 'machines', '斧钺': 'axes & halberds',
  '枪炮': 'guns & cannons', '钢铁': 'iron & steel', '头盔': 'helmets', '铠甲': 'armour',
  '硬壳食品': 'hard-shelled foods', '正财之星': 'star of honest wealth', '西医生': 'Western-medicine doctors',
  '西医药': 'Western medicine', '为首脑服务': 'serves the leadership', '攻于心计': 'adept at calculation',
  '具有智慧': 'possessed of wisdom', '善于治病': 'skilled at healing', '圆形': 'round shapes',
  '大吉(正财之星)': 'very auspicious (honest-wealth star)', '乳白': 'milky white', '头疼': 'headaches',
  '胸闷': 'chest tightness', '名医': 'famous doctors', '高官': 'high officials', '总裁': 'CEOs',
  '企业家': 'entrepreneurs', '决策者': 'decision-makers', '军官': 'officers', '有领导力': 'leaderly',
  '深谋远虑': 'far-sighted', '重情义': 'values loyalty', '有责任感': 'responsible',
  '秋高气爽': 'crisp autumn air', '天空清澈': 'clear skies', '明月': 'bright moon',
  '金属器物': 'metal utensils', '高档物品': 'premium goods', '公司总部': 'corporate HQs',
  '高档会所': 'exclusive clubs', '大型建筑': 'large buildings', '领导决策': 'executive decisions',
  '就医问药': 'seeking treatment', '求官求财': 'seeking office & wealth', '经营管理': 'management',
  '签约': 'signing contracts', '经营': 'operating business', '几乎百事皆宜': 'favourable for almost everything',
  '几乎无不宜': 'almost nothing unfavourable', '利于谋略': 'good for strategy', '君王': 'monarchs',
  '监管': 'oversight', '组织': 'organisation', '心计': 'calculation', '阳谋': 'open stratagems',
  '庙堂': 'halls of state', '哲学': 'philosophy', '道理': 'principles', '老成持重': 'seasoned & prudent',
  '策划缜密': 'meticulous planning', '领导组织': 'leading & organising', '化繁为条理': 'orders the complex',
  '学习方法': 'study methods', '管理经营': 'management & operations', '用心计': 'uses calculation',
  '咨询': 'consulting', '整合资源': 'integrating resources', '西医': 'Western medicine',
  '审计': 'auditing', '贵重物': 'valuables', '中心物': 'central things', '令印': 'seals of command',
  '市中心': 'city centres', '塔': 'towers', '金属物': 'metal objects', '西医器材': 'Western medical equipment',
  '开阔物': 'expansive things', '郊野': 'open country', '中平(小吉偏平)': 'neutral (mildly good)',
  '日升中天': 'sun at meridian', '万物生长': 'all things grow',
  '容易爆发争论争抢血光之灾': 'risk of disputes, scrambles & bloodshed', '面试': 'interviews',
  '考分': 'exam scores', '教练': 'coaches', '比分': 'scores', '酒业': 'liquor trade', '开会': 'meetings',
  '字据': 'written pledges', '景致': 'scenery', '风景': 'landscapes', '火电': 'thermal power',
  '计划': 'plans', '前景': 'prospects', '行情': 'market conditions', '打扮': 'dressing up',
  '美色': 'beauty & allure', '照片': 'photographs', '摄影': 'photography', '电脑显示器': 'computer monitors',
  '手机屏': 'phone screens', '相机': 'cameras', '各种装饰品': 'all kinds of ornaments',
  '各种家装': 'home décor', '旺于夏火': 'prospers in summer Fire', '相于春木': 'assisted in spring Wood',
  '休于季夏土': 'rests in late-summer Earth', '囚于秋金': 'trapped in autumn Metal', '死于冬水': 'dies in winter Water',
  '学术': 'scholarship', '华丽': 'gorgeous', '远景规划': 'long-range planning', '包装策划': 'packaging & promotion',
  '考卷': 'exam papers', '起诉书': 'indictments', '消息': 'news', '电子设备': 'electronics',
  '考试考卷': 'exams & papers', '宴席': 'banquets', '饮酒': 'drinking', '酒量': 'drinking capacity',
  '火器': 'firearms', '枪支': 'guns', '流血或血光事件': 'bloodshed incidents',
  '美丽色彩斑斓热闹': 'beautiful, colourful, bustling',
  '宜出谋献策选士荐贤火攻杀戮': 'good for counsel, selecting talent, fire attacks',
  '幻想': 'fantasies', '奇门遁甲也是景门': 'Qi Men itself belongs to the View Gate',
  '过于漂亮绚烂也为空想和幻想的来源': 'excessive splendour breeds fantasy', '美人': 'beauties',
  '宣传人员': 'publicists', '记者': 'journalists', '传媒人': 'media workers', '教育者': 'educators',
  '文化人': 'the cultured', '作家': 'writers', '文学家': 'literati', '诗人': 'poets',
  '影视演员': 'screen actors', '漂亮的人': 'good-looking people', '美容美发师': 'beauticians & stylists',
  '美容者': 'beauty clients', '旅游者': 'tourists', '烫伤者': 'scald victims', '烧伤者': 'burn victims',
  '电信类工作者': 'telecom workers', '电子产品生产经营者': 'electronics makers & sellers',
  '广告人': 'ad people', '策划人': 'planners', '影视行业': 'film & TV industry', '信息行业': 'information industry',
  '图书管理': 'librarianship', '文化部门': 'cultural departments', '影视传媒': 'screen media',
  '广告设计': 'ad design', '新闻信息': 'news & information', '票证业': 'ticketing & certificates',
  '美容业': 'beauty industry', '与火有关的行业': 'fire-related trades', '景色迷人': 'enchanting scenery',
  '选美模特活动': 'pageants & modelling', '脸色红润': 'rosy complexion', '亮丽的服饰': 'striking attire',
  '喜欢装扮的人': 'lovers of dressing up', '美丽华贵': 'beautiful & opulent', '追求美好': 'pursuing beauty',
  '有文采': 'literary flair', '乐观': 'optimistic', '有艺术气质': 'artistic temperament',
  '心直口快': 'frank & outspoken', '性格活跃': 'lively character', '脾气急躁': 'short-tempered',
  '虚心处事': 'modest in affairs', '知书达理': 'lettered & reasonable', '有思维修养': 'cultivated mind',
  '图书': 'books', '时装': 'fashion wear', '颜料': 'pigments', '美容美发用品': 'beauty & hair products',
  '书画用品': 'art supplies', '烟火爆竹': 'fireworks & crackers', '电影机': 'film projectors',
  '电视机': 'televisions', '投影机': 'projectors', '影视城': 'film studios', '风景区': 'scenic areas',
  '书画院': 'art academies', '灯火通明处': 'brightly lit places', '旅游景区': 'tourist spots',
  '繁华街道': 'busy streets', '戏院': 'playhouses', '电视制作发射中心': 'TV production & broadcast centres',
  '写作': 'writing', '宣传': 'publicity', '文艺演出': 'performances', '献策': 'offering counsel',
  '发表文章': 'publishing articles', '推荐贤良': 'recommending the worthy', '火攻杀敌': 'fire attacks',
  '献策筹谋': 'counsel & planning', '奏对': 'court replies', '选士荐贤': 'selecting talent',
  '拜职遣使': 'investitures & envoys', '口舌之争': 'verbal strife', '占断特征': 'divination traits',
  '利文不利武': 'favours the civil, not the martial', '利名不利实': 'favours fame over substance',
  '西方之阴金': 'yin Metal of the west', '暗中荫护': 'sheltering from the shadows', '保护神': 'guardian deity',
  '有隐匿性格': 'secretive nature', '显而不露': 'present but unseen', '好隐匿': 'fond of hiding',
  '具护佑之功': 'gives protection', '喜暗中行事': 'prefers covert action',
  '善作祯祥吉祥的好事': 'works quiet blessings', '多与女人阴私之事有关': 'tied to women’s private affairs',
  '其体柔': 'soft of body', '避凶': 'avoiding harm', '藏兵': 'hiding troops', '密谋策划': 'secret planning',
  '避难藏身': 'sheltering in hiding', '护佑': 'protection', '隐避': 'seclusion', '藏匿': 'concealment',
  '喜庆': 'festivity', '贞祥': 'chaste fortune', '淫乱': 'debauchery', '阴私': 'private secrets',
  '隐私': 'privacy', '密谋': 'conspiracy', '缜密': 'meticulous', '诅咒': 'curses', '忧疑': 'anxious doubt',
  '欺诈': 'fraud', '私通': 'illicit affairs', '遮盖': 'covering up', '雕刻': 'carving',
  '忧愁': 'sorrow', '思虑之事': 'matters of worry', '周密': 'thorough', '有秩序': 'orderly',
  '收获': 'harvest', '当兵': 'soldiering', '暗谋密约': 'secret pacts', '私通走失': 'affairs & disappearances',
  '典型女人形象': 'archetypal feminine figure', '见不得光': 'unfit for daylight', '女性贵人': 'female benefactors',
  '妻妾': 'wives & concubines', '阴谋策划者': 'plotters', '幕后之人': 'those behind the scenes',
  '暗中帮助者': 'hidden helpers', '女友': 'girlfriends', '二奶': 'mistresses', '私通者': 'illicit lovers',
  '雕刻师': 'carvers', '裁缝': 'tailors', '策划师': 'planners', '书画家': 'calligrapher-painters',
  '秘书': 'secretaries', '暗中行事者': 'covert operators', '隐居者': 'recluses', '祷告者': 'supplicants',
  '婢妾': 'maids & concubines', '暗中贵人': 'hidden benefactors', '冥助': 'unseen aid',
  '脸色白净': 'fair clear face', '口似樱桃': 'cherry mouth', '鼻子挺直': 'straight nose',
  '身白如玉': 'jade-white skin', '四指如葱': 'slender fingers', '温柔内敛': 'gentle & reserved',
  '隐忍含蓄': 'forbearing & subtle', '善于谋划': 'good at planning', '不露声色': 'gives nothing away',
  '品质优良': 'fine character', '正直慷慨': 'upright & generous', '助人为乐': 'delights in helping',
  '阴匿暗昧': 'hidden & obscure', '嘴': 'mouth', '腋下': 'armpits', '隐私部位': 'private parts',
  '涕液': 'mucus', '妇科': 'gynaecological', '暗疾': 'hidden ailments', '隐疾': 'unspoken ailments',
  '露雨': 'dew & rain', '阴霖': 'long overcast rains', '冰冻': 'freezing', '闺房': 'boudoirs',
  '后院': 'back courtyards', '阴面': 'shaded sides', '佛寺': 'Buddhist temples', '山的阴面': 'shaded mountainsides',
  '看不见光的房屋': 'lightless rooms', '隐藏之物': 'hidden things', '私房钱': 'secret savings',
  '密函': 'sealed letters', '帷幕': 'curtains & veils', '遮蔽之物': 'concealing things', '雕琢品': 'carved works',
  '字迹': 'handwriting', '墨迹': 'ink traces', '喜庆用品': 'festive goods', '冷饮': 'cold drinks',
  '车': 'carts & cars', '碾碎机': 'crushers', '内衣': 'underwear', '阴宅': 'gravesites',
  '精致细致物品': 'fine delicate items', '老鼠': 'rats', '猫头鹰等夜间出没的动物': 'owls & other nocturnal animals',
  '带壳的果实': 'shelled fruits', '瓜子': 'melon seeds', '苔藓植物': 'mosses', '沼泽生长的植物': 'marsh plants',
  '苇子': 'reeds', '蒲草': 'cattails', '私下交易': 'private deals', '隐蔽进行': 'done under cover',
  '暗中帮助': 'helping covertly', '宜暗不宜明': 'better hidden than open', '利于私下进行': 'best done privately',
  '有女贵人暗中相助': 'a female benefactor helps unseen', '灰色': 'grey', '暗绿': 'dark green',
  '苍': 'pale grey-green', '碧': 'jade blue', '翠绿': 'emerald green', '浅绿': 'light green',
  '青碧': 'azure jade', '曲': 'curved', '弯': 'bent', '希望达成': 'hopes fulfilled', '质软': 'soft in substance',
  '转机': 'turning points', '艺术': 'art', '柔弱': 'frail', '曲折': 'twists & turns', '依附': 'attachment',
  '绿色植物': 'green plants', '骑墙': 'fence-sitting', '没有主见': 'no mind of one’s own',
  '沟通': 'communication', '同情': 'sympathy', '理解': 'understanding', '倾听': 'listening',
  '淋巴': 'lymph', '输卵管': 'fallopian tubes', '输精管': 'vas deferens', '颈': 'neck', '腿': 'legs',
  '手腕': 'wrists', '脚腕': 'ankles', '经脉': 'meridian channels', '颈项': 'nape', '朴实': 'plain & honest',
  '柔情': 'tenderness', '儒雅': 'scholarly grace', '依赖': 'dependence', '忧郁敏感': 'melancholic & sensitive',
  '逆来顺受': 'submits to adversity', '善于攀附': 'good at climbing socially', '灵活': 'agile',
  '苗条': 'slender', '驼背身': 'stooped frame', '皮肤白嫩': 'fair tender skin', '骨质松弛': 'loose bones',
  '瘦长脸': 'long thin face', '得令时茂盛': 'lush in season', '失令时枯萎': 'withered out of season',
  '草地': 'lawns', '果林': 'orchards', '菜园': 'vegetable gardens', '艺术馆': 'art galleries',
  '漂亮的建筑物': 'handsome buildings', '矮林': 'low woods', '花圃': 'flower beds', '果园': 'orchards',
  '妃嫔': 'imperial consorts', '中医': 'TCM physicians', '画师': 'painters', '学士': 'scholars',
  '秀才': 'licentiates', '贤妻良母': 'good wives & mothers', '蚕虫': 'silkworms', '鸟类': 'birds',
  '蚕': 'silkworms', '小树': 'saplings', '水果树': 'fruit trees', '藤蔓细嫩植物': 'tender vines',
  '黄瓜': 'cucumbers', '柳枝': 'willow twigs', '龙爪槐': 'weeping pagoda trees', '兰花': 'orchids',
  '盆景': 'bonsai', '茶叶': 'tea leaves', '竹编': 'bamboo weaving', '雕梁画柱': 'carved beams & painted pillars',
  '木雕': 'wood carvings', '油画': 'oil paintings', '办公桌': 'desks', '藤椅': 'rattan chairs',
  '管道拐弯处': 'pipe bends', '楼梯': 'staircases', '面条': 'noodles', '禾苗': 'seedlings',
  '软木条': 'soft wood strips', '藤条': 'rattan canes', '绿地': 'green spaces', '栏杆': 'railings',
  '毛笔': 'writing brushes', '织物': 'textiles', '手作': 'handcrafts', '纸张': 'paper', '丝绢': 'silk',
  '胀': 'bloating', '甜酸': 'sweet & sour',
});

/* Batch 5 — Tianchong, Open/Shock/Death gates, Tianpeng, Tianren, White Tiger,
   Black Tortoise, Harmony, remaining traits & places. */
Object.assign(window.QMS_TERMS_EN, {
  '勇武之星': 'star of valour', '发射': 'launching', '起飞': 'takeoff', '小吉(勇武之星)': 'mildly auspicious (valour star)',
  '筋骨损伤': 'sinew & bone injuries', '开拓者': 'pioneers', '勇士': 'the brave', '探险家': 'explorers',
  '冒险家': 'adventurers', '急躁冲动': 'impatient & impulsive', '直爽正义': 'frank & righteous',
  '性刚': 'hard-natured', '有冲劲': 'driven', '缺耐性': 'short on patience', '雷': 'thunder',
  '暴风雨': 'storms', '兵器': 'weapons', '战鼓': 'war drums', '竹木器具': 'bamboo & wood utensils',
  '运动器材': 'sports equipment', '操场': 'playgrounds', '运动场': 'sports grounds',
  '林木茂盛处': 'lush woods', '征伐': 'campaigns', '体育': 'sports', '冒险': 'adventure',
  '竞技': 'athletics', '安静守成': 'quiet preservation', '养病': 'convalescing',
  '利于点将出师': 'good for marshalling & marching', '击鼓攻战': 'drumming the attack',
  '冬春时节利于农事': 'winter-spring favours farm work', '利于助人': 'good for helping others',
  '次要的吉祥之星': 'a lesser lucky star', '冲击': 'impact', '冲撞': 'collision', '快速': 'swift',
  '敏捷': 'nimble', '急迫': 'urgent', '涌动': 'surging', '鲁莽': 'reckless', '直接': 'direct',
  '冒失': 'rash', '早泄': 'premature ejaculation', '快枪手': 'quick-draw types', '没耐心': 'impatient',
  '不稳重': 'unsteady', '快速变化': 'rapid change', '新鲜刺激': 'fresh thrills', '临机应变': 'improvises well',
  '武行': 'martial professions', '商店': 'shops', '科技': 'technology', '交通物': 'transport things',
  '高大物': 'tall things', '飞船': 'spacecraft', '竹子': 'bamboo', '鸣叫物': 'crowing things',
  '噪动物': 'noisy animals', '蟋蟀': 'crickets', '羚羊': 'antelopes', '松鼠': 'squirrels',
  '开创事业从开门位开始': 'ventures start from the Open Gate', '公开不能保密': 'public, cannot stay secret',
  '开始': 'beginnings', '最初': 'the very first', '原始': 'primal', '开创': 'founding',
  '创始人': 'founders', '门面': 'storefronts', '官运': 'career fortune', '打开可以出来': 'opening releases',
  '旷野': 'open wilds', '大房': 'great houses', '大平层': 'large flats', '公共场所': 'public places',
  '秘密遇到开门必然泄密': 'secrets met by Open Gate must leak', '广阔空间': 'broad spaces',
  '无拘束': 'unconstrained', '旅行': 'travel', '出差': 'business trips', '扩展视野': 'broadening horizons',
  '旺于秋金': 'prospers in autumn Metal', '相于季夏土': 'assisted in late-summer Earth',
  '休于冬水': 'rests in winter Water', '囚于春木': 'trapped in spring Wood', '死于夏火': 'dies in summer Fire',
  '开放': 'openness', '开明': 'enlightened', '开朗': 'cheerful', '打开': 'opening',
  '开工典礼': 'groundbreaking ceremonies', '亮相': 'public debuts',
  '开门具有开始公开开放的意思': 'Open Gate means beginnings, publicity, openness',
  '代表政府机关单位文职官员工厂公司商店': 'represents government bodies, civil officials, factories, firms, shops',
  '工作事业上级领导法院法官': 'work, career, superiors, courts & judges', '泄密': 'leaks',
  '清晰': 'clarity', '明朗': 'lucid', '爽达': 'breezy & open', '金色': 'gold colour', '头痛': 'headaches',
  '重病手术多主开刀': 'grave illness often means surgery', '官员': 'officials', '开创者': 'founders',
  '具有开拓精神的人': 'pioneering spirits', '文职官员': 'civil officials', '白领': 'white-collar workers',
  '公司企业老板': 'company bosses', '脸方顶圆': 'square face, round crown', '鼻正口方': 'straight nose, square mouth',
  '上身长直': 'long straight torso', '大方豁达': 'gracious & open-minded', '有领导才能': 'leadership talent',
  '气度恢宏': 'grand bearing', '豁达爽朗': 'open & hearty', '谈吐不凡': 'distinguished speech',
  '坦诚无私': 'candid & selfless', '性情愉快': 'cheerful disposition', '无所拘束': 'unrestrained',
  '意志活跃': 'active will', '思想开放': 'open-minded', '通情达理': 'reasonable', '容易沟通': 'easy to talk to',
  '讲情重义': 'values bonds & loyalty', '自尊心强': 'strong self-respect', '勤奋好学': 'diligent & studious',
  '公司': 'companies', '大门口': 'main gates', '开阔之地': 'open ground', '大厅': 'halls',
  '矿场': 'mining sites', '工作单位': 'workplaces', '店铺': 'shops', '门市': 'storefronts',
  '审判庭': 'courtrooms', '创办': 'founding', '建立': 'establishing', '领导管理': 'leadership & management',
  '开工': 'starting work', '万事皆宜': 'favourable for all things', '考学': 'school entrance',
  '见官': 'meeting officials', '做事': 'getting things done', '觅人': 'seeking people', '参军': 'enlisting',
  '婚娶': 'marrying', '进口': 'imports', '天高云淡': 'high skies, thin clouds', '使用条件': 'conditions of use',
  '水之精': 'essence of Water', '统辖北方之气': 'governs the northern qi', '奸馋小盗之神': 'deity of sneaks & petty thieves',
  '好阴谋': 'fond of plots', '贼害': 'thievery & harm', '虚伪的小偷小摸之神': 'deity of furtive pilfering',
  '深奥': 'abstruse', '玄虚': 'mystified', '不可靠': 'unreliable', '不可捉摸': 'elusive',
  '玄妙': 'arcane', '领悟': 'insight', '偷盗': 'theft', '偷情': 'affairs', '谎言': 'lies',
  '诡计': 'ruses', '文章技巧': 'literary craft', '啼哭': 'wailing', '梦想': 'dreams', '离别': 'parting',
  '遗失': 'losses', '逃人': 'runaways', '奸邪': 'the wicked', '色情': 'eroticism', '玄学': 'mysticism',
  '不明白': 'incomprehension', '黑暗': 'darkness', '影子': 'shadows', '乞讨': 'begging', '偷看': 'peeping',
  '头晕': 'dizziness', '醉酒': 'drunkenness', '昏迷': 'coma', '淫邪': 'lechery', '迷糊': 'muddled',
  '吹嘘': 'bragging', '夸大宣传': 'hype', '暗昧之事': 'shady matters', '盗耗': 'losses to theft',
  '黑暗伸手不见五指': 'pitch darkness', '道听途说': 'hearsay', '悬挂': 'hanging',
  '挂在高处不踏实': 'hung high and unsteady', '小偷': 'thieves', '骗子': 'swindlers', '奸细': 'moles',
  '暗探': 'spies', '淫邪之人': 'the lecherous', '不诚实之人': 'the dishonest', '聪明多智者': 'the clever',
  '能言善辩者': 'the silver-tongued', '文艺人才': 'artistic talents', '诚信不高者': 'the untrustworthy',
  '爱说谎话者': 'habitual liars', '文士': 'men of letters', '醉客': 'drunkards', '导演': 'directors',
  '娼妇': 'harlots', '水产经营者': 'seafood dealers', '奸诈小人': 'treacherous schemers',
  '贼眉鼠眼': 'shifty-eyed', '神色不定': 'unsettled look', '弯腰驼背': 'stooped', '肩窄腿细': 'narrow shoulders, thin legs',
  '视力衰退': 'failing eyesight', '奸诈狡猾': 'sly & deceitful', '偷偷摸摸': 'furtive',
  '暧昧不清': 'murky', '不守信': 'faithless', '机智灵活': 'quick & adaptable', '聪明多智': 'clever & wily',
  '巧言善辩': 'glib', '干练虚伪': 'capable but false', '偷奸取巧': 'cuts corners', '聪明而躁急': 'clever but hasty',
  '巧辩而反复': 'glib and fickle', '泌尿生殖': 'urogenital', '女子阴私': 'women’s private matters',
  '体液': 'bodily fluids', '黑夜': 'night', '阴暗': 'gloom', '黑天': 'dark skies',
  '盗贼出没之地': 'thieves’ haunts', '赌场': 'casinos', '色情场所': 'red-light venues', '阴沟': 'gutters',
  '粪便': 'excrement', '赃物': 'loot', '伪造之物': 'forgeries', '偷盗工具': 'burglary tools',
  '印信': 'seals', '酱': 'sauces', '油': 'oil', '伞': 'umbrellas', '碳': 'charcoal',
  '一切流体类物质': 'all fluids', '瓶': 'bottles', '罐': 'jars', '瓢': 'ladles', '缸等容器': 'vats & vessels',
  '黑色物质': 'black substances', '赝品': 'fakes', '鱼类': 'fish', '喜水动物': 'water-loving animals',
  '水草': 'waterweed', '紫菜': 'laver', '含水量大的植物': 'watery plants', '诈骗': 'scams',
  '失窃': 'burglary', '暗中破坏': 'sabotage', '主盗窃欺诈阴私暗昧': 'augurs theft, fraud & shady dealings',
  '物有遗失': 'things go missing', '须防小人': 'beware of schemers', '玄色': 'deep black',
  '亮蓝': 'bright blue', '海蓝': 'sea blue', '湖蓝': 'lake blue', '墨色': 'ink black',
  '无规则': 'irregular', '迷惘': 'bewilderment', '迁移': 'migration', '因境变化': 'change with circumstance',
  '物流': 'logistics', '化学工业': 'chemical industry', '享受思考问题的状态': 'enjoys deep thought',
  '容易迷失在逻辑中': 'easily lost in logic', '忽视现实': 'ignores reality', '不堪现实的大用': 'unfit for practical heavy use',
  '风流浪荡': 'rakish', '发': 'hair', '动脉': 'arteries', '宫胞': 'womb', '小腿': 'calves',
  '循环系统': 'circulatory system', '生殖系统': 'reproductive system', '胫骨': 'shinbones',
  '血液循环': 'blood circulation', '聪明机智': 'clever & quick', '善于谋略': 'good at strategy',
  '圆滑变通': 'smooth & flexible', '放荡不羁': 'unbridled', '好动不定': 'restless', '柔险': 'soft peril',
  '任性': 'wilful', '风流': 'amorous', '可共患难但难同甘共乐': 'shares hardship, not joy', '勇敢': 'brave',
  '多智': 'wily', '纵欲': 'indulgent', '容纳': 'containing', '随遇而安': 'at ease anywhere',
  '皮肤稍黑': 'darkish skin', '大眼睛': 'big eyes', '双眼皮': 'double eyelids', '走路摇摆': 'swaying gait',
  '长发秀眉': 'long hair, fine brows', '得令时助人利物': 'aids people in season', '失令时妨人害国': 'harms out of season',
  '海啸': 'tsunamis', '台风': 'typhoons', '江': 'great rivers', '河': 'rivers', '湖': 'lakes',
  '海': 'seas', '人流': 'crowds', '电影': 'films', '礼堂': 'auditoriums', '港口': 'harbours',
  '水库': 'reservoirs', '瀑布': 'waterfalls', '水产者': 'aquaculture workers', '养殖者': 'breeders',
  '航海者': 'seafarers', '海员': 'sailors', '流氓': 'hooligans', '渔猎者': 'fisher-hunters',
  '流动人员': 'transients', '航海家': 'navigators', '旅行家': 'travellers', '水中物': 'things in water',
  '水中大型动物': 'large aquatic animals', '菱角': 'water caltrops', '海草': 'seagrass', '水藻': 'algae',
  '莲藕': 'lotus roots', '水生植物': 'aquatic plants', '被子': 'quilts', '灯罩': 'lampshades',
  '干净的水': 'clean water', '自来水': 'tap water', '水管': 'water pipes', '消防用品': 'firefighting gear',
  '船舶': 'ships', '水车': 'waterwheels', '水缸': 'water vats', '墨汁': 'ink', '染料': 'dyes',
  '电脑水冷散热系统': 'liquid cooling systems', '有温度的液体': 'warm liquids', '胀痛': 'swelling pain',
  '厚重之星': 'star of solidity', '稳重之人': 'the steady', '厚道之人': 'the kindly',
  '隆冬将过': 'deep winter passing', '春天将临': 'spring approaching', '万物萌生': 'all things sprout',
  '小吉(厚重之星)': 'mildly auspicious (solidity star)', '关节': 'joints', '脾胃不和': 'spleen-stomach discord',
  '关节炎': 'arthritis', '手指伤': 'finger injuries', '背痛': 'backache', '鼻疾': 'nasal ailments',
  '结石': 'stones (calculi)', '忠厚老实之人': 'the honest & sincere', '慈善家': 'philanthropists',
  '少年': 'youths', '胖人': 'the stout', '性格内敛': 'reserved nature', '不善言辞': 'inarticulate',
  '任劳任怨': 'uncomplaining', '勤劳守信': 'diligent & true', '云雾缭绕': 'wreathed in mist',
  '薄雪': 'light snow', '山中气候': 'mountain weather', '山石': 'mountain rocks', '土产品': 'local produce',
  '建筑材料': 'building materials', '坚固之物': 'sturdy things', '秤': 'scales', '丘陵': 'hills',
  '储存室': 'storerooms', '山间小路': 'mountain paths', '建筑土木': 'civil engineering', '矿业': 'mining',
  '储蓄': 'savings', '不动产': 'real property', '山林经济': 'forestry economy', '建筑修造': 'building & repair',
  '积蓄': 'accumulation', '安家': 'settling a home', '急事': 'urgent matters', '投机冒险': 'speculation & risk',
  '利于安民': 'good for calming the people', '立都': 'founding capitals', '当官': 'holding office',
  '教育民众': 'educating the people', '从商': 'going into trade', '诸事吉祥': 'all things auspicious',
  '农夫': 'farmers', '工人': 'workers', '老实': 'honest', '承担': 'shouldering', '责任': 'responsibility',
  '呆板': 'wooden', '辛劳': 'toil', '魅力低': 'low charisma', '性张力差': 'low magnetism',
  '性能力低': 'low virility', '怕老婆': 'henpecked', '强为高管': 'strong: executives', '弱为工人': 'weak: labourers',
  '无风险': 'riskless', '听令于人': 'takes orders', '工业': 'industry', '农业': 'agriculture',
  '制造业': 'manufacturing', '矿产': 'mineral resources', '土木': 'construction', '铺垫物': 'underlays',
  '依靠物': 'supports', '收容物': 'receptacles', '椅': 'chairs', '桌': 'tables', '被': 'quilts',
  '柜': 'cabinets', '缓变物': 'slow-changing things', '起伏物': 'undulating things', '梯': 'ladders',
  '丘': 'mounds', '台阶': 'steps', '起伏道路': 'rolling roads', '朴实物': 'plain things',
  '山中物': 'mountain things', '稻谷': 'paddy rice', '城隍土地': 'city & earth gods', '山果': 'mountain fruits',
  '外貌': 'appearance', '胖': 'plump', '肉厚': 'thick-fleshed', '脸黄': 'sallow face',
  '兑金宫': 'Dui Metal palace', '秋气肃杀': 'austere autumn air', '草木凋零': 'withering vegetation',
  '令人惊心': 'startling', '争论争吵': 'arguments & quarrels', '令人紧张焦虑惊恐': 'breeds tension & dread',
  '主惊恐创伤官非之事': 'augurs fright, trauma & legal trouble', '演唱': 'singing', '相声': 'crosstalk comedy',
  '主持人': 'hosts & MCs', '游戏': 'games', '设疑': 'sowing doubt', '伏兵': 'ambush troops',
  '蛊惑人心': 'beguiling the crowd', '破损': 'breakage', '吃饭': 'dining', '能说会道': 'gift of the gab',
  '说大话': 'tall talk', '恐吓': 'intimidation', '主播': 'streamers & anchors', '导游': 'tour guides',
  '说唱rap': 'rap', '风铃': 'wind chimes', '蝉': 'cicadas', '高风险的投资': 'high-risk investment',
  '投机': 'speculation', '比赛': 'contests', '派出所': 'police posts', '妖异': 'eerie wonders',
  '怪事': 'strange affairs', '语不惊人死不休': 'shocks with every word', '标题党': 'clickbait',
  '大新闻': 'big news', '闹市区': 'downtown bustle', '演唱会': 'concerts', '人多的体育场': 'packed stadiums',
  '奇怪': 'odd', '刺激': 'thrills', '吃惊': 'astonishment', '诧异': 'surprise', '惊慌': 'panic',
  '恐慌': 'terror', '声音': 'sounds', '惊门具有惊恐口舌口才争斗的含义': 'Shock Gate means fright, gossip, eloquence & strife',
  '代表口舌官司口才说喝有关职业': 'represents speech, lawsuits & vocal professions',
  '惊门宜斗讼捕盗争论': 'Shock Gate favours litigation, thief-catching & debate', '舌疾': 'tongue ailments',
  '受惊': 'taking fright', '心悸': 'palpitations', '受惊之人': 'the startled', '精神病患': 'the mentally ill',
  '口舌是非之人': 'gossipmongers', '告密者': 'informers', '讲师': 'lecturers', '播音员': 'broadcasters',
  '教育部门': 'education departments', '纪检监察人员': 'discipline inspectors', '惊恐万分': 'terrified',
  '瞠目结舌状': 'agape', '一鸣惊人': 'astonishes at one stroke', '嘴闭不上': 'mouth never shut',
  '呆若木鸡状': 'dumbstruck', '惊慌失措': 'panicked', '多疑善惊': 'jumpy & suspicious', '口舌多': 'much gossip',
  '好争辩': 'argumentative', '心神不安': 'uneasy spirit', '声音宏亮': 'resonant voice',
  '担惊受怕': 'living in fear', '忐忑不安': 'on edge', '心事重重': 'burdened heart', '钟': 'bells',
  '一切能发声的物体': 'all sound-making objects', '法庭': 'courtrooms', '喧哗之地': 'clamorous places',
  '噪音大的场所': 'noisy venues', '球场': 'ball courts', '草场': 'meadows', '乐器厂': 'instrument factories',
  '炸药厂': 'explosives plants', '一切能够发声的场所': 'all sounding venues', '告状': 'filing complaints',
  '诉讼(原告方)': 'lawsuits (as plaintiff)', '威慑': 'deterrence', '打官司': 'litigating',
  '抓盗贼': 'catching thieves', '斗讼官司': 'contentious lawsuits', '掩捕盗贼': 'ambushing thieves',
  '蛊惑乱众': 'rabble-rousing', '赌博游戏': 'gambling games', '其余事不可为': 'all else inadvisable',
  '西方阳金': 'yang Metal of the west', '凶煞之神': 'deity of menace', '凶狠好斗': 'fierce & combative',
  '好杀': 'fond of killing', '专管兴兵打仗': 'governs raising armies', '凶杀打斗': 'killings & brawls',
  '形锐利': 'sharp of form', '凶猛': 'ferocious', '刚毅': 'resolute', '严肃': 'stern', '艳丽': 'gorgeous',
  '强硬': 'hardline', '犯罪': 'crime', '重病': 'grave illness', '凶伤孝服': 'injury & mourning',
  '行凶打人': 'assault', '死丧': 'death & mourning', '威权': 'authority', '车祸': 'car crashes',
  '凶险快速': 'swift peril', '凶悍之人': 'the ferocious', '仇敌': 'enemies', '技术过硬之人': 'the masterly',
  '好斗之人': 'brawlers', '黑社会之人': 'gangsters', '威猛之人': 'the formidable', '权力之人': 'power-holders',
  '讲义气之人': 'the loyal-hearted', '高科技人员': 'hi-tech workers', '武警': 'armed police',
  '捕盗人': 'thief-takers', '罪犯': 'criminals', '重病人': 'the gravely ill', '侍卫': 'guards',
  '工匠': 'craftsmen', '牧童': 'herd boys', '捕役': 'constables', '强硬者': 'hardliners',
  '有手段者': 'the ruthless', '面部表情严肃或死板': 'stern or wooden expression', '身体多肌肉': 'muscular body',
  '强健之人': 'the robust', '刚猛凶悍': 'fierce & savage', '杀伐决断': 'decisive in the kill',
  '好斗威严': 'combative & stern', '暴烈急躁': 'violent & rash', '大义凛然': 'awesome righteousness',
  '残暴易怒': 'brutal & irascible', '决断冲突': 'decisive in conflict', '讲义气': 'loyal-hearted',
  '威雄猛烈': 'mighty & fierce', '拳头': 'fists', '外伤': 'external injuries', '刀伤': 'knife wounds',
  '霹雳': 'thunderclaps', '狂风': 'gales', '飓风': 'hurricanes', '火山喷发': 'volcanic eruptions',
  '冰雹': 'hail', '迅雷': 'sudden thunder', '屠宰场': 'slaughterhouses', '丧葬之地': 'burial grounds',
  '峭壁': 'cliffs', '房角': 'house corners', '路口': 'crossroads', '关口': 'passes',
  '刀枪剑戟': 'blades & polearms', '金属利器': 'sharp metal implements', '凶器': 'murder weapons',
  '白布': 'white cloth', '毒品': 'narcotics', '武器': 'weapons', '碾子': 'roller mills', '磨': 'millstones',
  '石狮子': 'stone lions', '铁质品': 'iron goods', '瓦石': 'tiles & stones', '网罗': 'nets & snares',
  '交通信号灯': 'traffic lights', '朽铁': 'rusted iron', '仿生武器': 'bionic weapons', '爆炸': 'explosions',
  '口红': 'lipstick', '豺': 'jackals', '大灰狼': 'grey wolves', '食肉动物': 'carnivores',
  '鱼鳖蛟龙': 'fish, turtles & dragons', '猪笼草': 'pitcher plants', '蒺藜草': 'puncture vines',
  '蝎子草': 'nettle herbs', '荆棘': 'brambles', '枣树': 'jujube trees', '杜梨树': 'birchleaf pears',
  '刺槐等能够使人和动物伤亡的一切植物': 'locusts & all plants that wound', '争斗': 'strife',
  '丧事': 'funerals', '主凶险血光刑伤破败': 'augurs peril, bloodshed & ruin', '须防灾祸': 'guard against calamity',
  '刺眼的光': 'glaring light', '淡红': 'pale red', '尖': 'pointed', '执著': 'fixated', '逼人': 'imposing',
  '带刺': 'thorny', '顶尖': 'top-tier', '突出': 'prominent', '尖声震惊': 'piercing shrieks',
  '思想': 'thought', '医道': 'the healing art', '神学': 'theology', '内心': 'the inner heart',
  '电子': 'electronics', '名望': 'renown', '闪烁': 'flickering', '奇迹': 'miracles',
  '连贯中的不连贯': 'breaks within continuity', '普遍中的不普遍': 'the exceptional within the common',
  '肉刺': 'hangnails', '齿': 'teeth', '文明有礼': 'civil & courteous', '内敛含蓄': 'reserved & subtle',
  '坚韧不拔': 'tenacious', '文雅': 'refined', '多思': 'pensive', '有心机': 'calculating',
  '和顺': 'amiable', '体贴': 'thoughtful', '洞察奸邪': 'sees through villainy', '秀丽清高': 'graceful & aloof',
  '肤白粉嫩': 'fair tender skin', '发细而长': 'fine long hair', '额宽而尖': 'wide tapering brow',
  '得令时明察秋毫': 'eagle-eyed in season', '失令时忧愁焦虑': 'anxious out of season', '星光': 'starlight',
  '烛光': 'candlelight', '月光': 'moonlight', '屋檐': 'eaves', '屋角': 'roof corners', '房顶': 'rooftops',
  '文化中心': 'cultural centres', '案台': 'altars & desks', '灯塔': 'lighthouses', '电子城': 'electronics malls',
  '谋臣': 'counsellors', '幕僚': 'aides', '中年女性': 'middle-aged women', '技术一流之人': 'first-rate technicians',
  '表现突出之人': 'standout performers', '说话带刺之人': 'barbed speakers', '修道者': 'cultivators of the Way',
  '情感中的小三': 'the third party in love', '螃蟹': 'crabs', '马蜂': 'hornets', '蜜蜂': 'bees',
  '牛虻': 'gadflies', '野猪': 'wild boars', '带刺植物或果实': 'thorny plants & fruits', '玫瑰': 'roses',
  '月季': 'china roses', '槐树': 'pagoda trees', '仙人掌': 'cacti', '松树': 'pines', '石榴': 'pomegranates',
  '板栗': 'chestnuts', '毛丹': 'rambutans', '榛子': 'hazelnuts', '红枫': 'red maples', '灯笼草': 'lantern plants',
  '发光体': 'luminous bodies', '弱热体': 'mildly warm bodies', '刀': 'knives', '剑': 'swords',
  '注射器': 'syringes', '钉子': 'nails', '牙签': 'toothpicks', '票据': 'receipts & notes', '拐杖': 'canes',
  '电子产品': 'electronic products', '烛台': 'candlesticks', '打火机': 'lighters', '炮弹': 'shells',
  '子弹': 'bullets', '小型金属物件': 'small metal items', '焰火': 'fireworks', '报刊': 'newspapers & journals',
  '突出独特性的短视频': 'distinctive short videos', '小点心': 'small pastries', '精致食品': 'fine foods',
  '盗贼之星': 'star of thieves', '强盗之星': 'star of bandits', '要犯': 'wanted criminals',
  '黑帮老大': 'crime bosses', '喜阴': 'shade-loving', '喜冬': 'winter-loving', '怕阳': 'sun-shy',
  '与大盗在暗中出没有关': 'tied to great thieves in the dark', '水肿': 'oedema', '中毒': 'poisoning',
  '赌徒': 'gamblers', '犯人': 'convicts', '江湖人': 'drifters of the jianghu', '诈骗犯': 'fraudsters',
  '酒徒': 'tipplers', '潜水员': 'divers', '胆大妄为': 'recklessly bold', '狡诈多谋': 'cunning & scheming',
  '好色贪杯': 'lustful & bibulous', '心狠手辣': 'ruthless', '大雪': 'heavy snow', '霜冻': 'frost',
  '水灾': 'floods', '毒药': 'poisons', '黑色器物': 'black utensils', '污水处': 'sewage sites',
  '夜总会': 'nightclubs', '走私': 'smuggling', '私密活动': 'private activities', '暗中谋划': 'covert plotting',
  '布局设伏': 'laying ambushes', '容易遇到盗贼': 'likely to meet thieves', '破产': 'bankruptcy',
  '生病': 'falling ill', '可以屯兵防守': 'fit for garrison defence', '加固城池': 'fortifying walls',
  '游侠': 'roaming knights', '胆魄': 'daring', '好色': 'lustful', '浪荡': 'dissolute', '多变': 'changeable',
  '贪大': 'overreaching', '雄略': 'grand stratagems', '魅力': 'charisma', '性张力': 'magnetism',
  '情种': 'romantics', '强力边将': 'mighty frontier generals', '弱为黑道': 'weak: the underworld',
  '有风险': 'risky', '突破边界': 'crossing boundaries', '恣意捞偏门': 'wanton shady gains',
  '风月场所': 'pleasure quarters', '洗浴': 'bathhouses', '餐饮': 'catering', '水产养殖': 'aquaculture',
  '蓬松物': 'fluffy things', '蓬状物': 'tufted things', '棚': 'sheds', '顶': 'roofs', '亭': 'pavilions',
  '桥': 'bridges', '娱乐场': 'amusement venues', '透风房': 'draughty rooms', '雨棚': 'rain awnings',
  '天棚': 'canopies', '多毛物': 'hairy things', '水生物': 'aquatic life', '蘑菇': 'mushrooms',
  '伞叶植物': 'umbrella-leaved plants', '人物例': 'example figures', '刘备': 'Liu Bei', '刘邦': 'Liu Bang',
  '曹操': 'Cao Cao', '川普': 'Trump', '西南方': 'southwest', '坤土宫': 'Kun Earth palace',
  '春生秋实': 'spring growth, autumn fruit', '收割之季': 'harvest season', '巨大阻力': 'great resistance',
  '不利吉事': 'bad for festive matters', '只宜吊死送丧刑戮争战捕猎杀牲': 'fit only for mourning, executions, war & slaughter',
  '地皮': 'land parcels', '地产': 'real estate', '地段': 'locations', '刑戮': 'executions',
  '伤疤': 'scars', '痛苦': 'suffering', '死气沉沉': 'lifeless', '死亡之信息': 'tidings of death',
  '结束': 'endings', '最终': 'the final', '最后': 'the last', '死者': 'the dead', '尸体': 'corpses',
  '锁头': 'padlocks', '执着': 'fixation', '不灵活': 'inflexible', '死心眼': 'one-track stubbornness',
  '死板': 'rigid', '没有变化': 'changeless', '丧失生命': 'loss of life', '没有生命': 'lifeless things',
  '不可调和': 'irreconcilable', '固定不变': 'fixed', '不可周转': 'untradeable', '断了念头': 'hopes severed',
  '鬼神': 'ghosts & spirits', '代表房地产土地地基死人坟地凶灾死亡神佛': 'represents land, graves, calamity, death & deities',
  '如果是开矿业遇死门则可暴富': 'in mining, Death Gate can bring sudden riches',
  '死门宜吊死送丧安葬刑戮战争': 'Death Gate suits mourning, burial, executions & war', '痕迹': 'traces',
  '疤痕': 'scars', '古老': 'ancient', '学习古老教条知识': 'studying old doctrines',
  '人形玩偶和雕塑无生命': 'lifeless dolls & statues', '阴间范': 'netherworld air', '肌肤': 'skin',
  '没有活力的部位': 'lifeless parts', '病灶部位': 'lesion sites', '死疤': 'dead scars', '肿块': 'lumps',
  '慢性顽疾': 'chronic stubborn illness', '丧家': 'bereaved households', '殡葬人员': 'undertakers',
  '吊唁者': 'mourners', '阴沉之人': 'the sombre', '思想不开放的人': 'the closed-minded',
  '已经故去的人': 'the departed', '执着的人': 'the fixated', '不灵活的人': 'the inflexible',
  '死板的人': 'the rigid', '不能变通的人': 'the unadaptable', '和尚': 'monks',
  '无药可救的人': 'the incorrigible', '行刑之人': 'executioners', '救死扶伤的人': 'healers of the dying',
  '土建部门': 'civil-works departments', '丧葬部门': 'funeral services', '医务人员': 'medics',
  '行刑人': 'executioners', '各类开矿业': 'mining of all kinds', '脸色呆板木纳': 'wooden expression',
  '倔强不灵活': 'stubbornly inflexible', '不开心': 'unhappy', '呆头呆脑的人': 'dull-witted people',
  '保守固执': 'conservative & stubborn', '不会变通的人': 'the unbending', '消沉': 'dejected',
  '悲观': 'pessimistic', '沉闷': 'gloomy', '无生气': 'lifeless', '心如死灰': 'heart of dead ashes',
  '固执保守': 'stubbornly conservative', '缺乏生命力': 'lacking vitality', '死不认账': 'denies to the end',
  '一条路走到黑': 'rides one road into the dark', '固执己见': 'opinionated', '雕塑': 'sculptures',
  '偶像': 'idols', '木偶': 'puppets', '死人照片': 'photos of the dead', '枪': 'guns', '炸弹': 'bombs',
  '枷锁': 'shackles', '墓碑': 'gravestones', '俑': 'burial figurines', '废弃物': 'refuse',
  '废屋': 'derelict houses', '废井': 'disused wells', '空置房': 'vacant homes', '亡人照': 'portraits of the deceased',
  '棺木': 'coffins', '保险柜中黄金': 'gold in safes', '囤积的应急物品': 'hoarded emergency supplies',
  '牛羊': 'cattle & sheep', '松柏': 'pines & cypresses', '殡仪馆': 'funeral parlours', '死胡同': 'dead ends',
  '火葬厂': 'crematoria', '玩具厂': 'toy factories', '雕塑厂': 'sculpture works', '不住人的空房': 'uninhabited rooms',
  '停尸间': 'mortuaries', '吊唁': 'condolence calls', '捕杀': 'hunting down', '结束之事': 'matters ending',
  '钓鱼': 'fishing', '吊死': 'hangings', '捕捉': 'capturing', '刑杀': 'executions', '捕猎': 'hunting',
  '一切喜庆': 'all festivities', '东方木神': 'wood deity of the east', '甲木之化气': 'transformed qi of Jia Wood',
  '多方面保护神': 'many-sided guardian', '性和平': 'peaceable nature',
  '专司婚姻交易媒人和合之事': 'governs marriage, trade, matchmaking & union', '又为护卫之神': 'also a guardian deity',
  '利交易谈判中介合作婚娶': 'good for deals, mediation, partnership & marriage', '欢乐': 'joy',
  '祥和': 'harmony', '联合': 'alliance', '交易': 'transactions', '结婚': 'marriage', '众多': 'multitudes',
  '收拢': 'gathering in', '平和': 'placid', '共同': 'shared', '适合': 'suitable', '合抱': 'embracing',
  '重叠': 'overlapping', '相聚': 'gathering', '聚集': 'congregating', '开朗平和': 'cheerful & placid',
  '恋爱': 'courtship', '婚姻嫁娶': 'marriage & weddings', '爵禄荣庆': 'rank, salary & celebration',
  '争财': 'wealth disputes', '致疾': 'causing illness', '胆怯': 'timidity', '同谋': 'complicity',
  '求降': 'seeking surrender', '勾引': 'seduction', '人缘好的': 'the well-liked', '亲吻': 'kissing',
  '亲善力很强': 'strong affability', '母子关系': 'mother-child bonds', '握手': 'handshakes',
  '拥抱': 'embraces', '清纯': 'pure & fresh', '光彩': 'lustre', '人与人的亲密关系': 'human intimacy',
  '鱼水之欢': 'conjugal joy', '能开合': 'opens and closes', '媒人': 'matchmakers', '合伙人': 'partners',
  '经纪人': 'agents', '谈判者': 'negotiators', '乐善好施之人': 'the charitable',
  '人缘好的人': 'the well-connected', '组织能力强的人': 'strong organisers', '儿童': 'children',
  '幼儿': 'infants', '基督徒': 'Christians', '信教人': 'believers', '行人走失': 'missing travellers',
  '贤士': 'the worthy', '娼女': 'courtesans', '魔术师': 'magicians', '子孙': 'descendants',
  '兔牙': 'buck teeth', '一团和气': 'all geniality', '笑容可掬': 'beaming', '点头哈腰': 'bowing & scraping',
  '缩头耸肩': 'shrugging timidity', '和蔼可亲': 'amiable', '圆融通达': 'smoothly versed',
  '讲究合作': 'values cooperation', '仁慈谦让': 'kind & yielding', '荐贤不妒': 'promotes talent without envy',
  '喜做说合之事': 'loves matchmaking', '人际关系良好': 'good relationships', '脚趾': 'toes',
  '眉毛': 'eyebrows', '主可调和': 'augurs reconcilability', '温暖气候': 'warm climate', '旭日': 'rising sun',
  '婚姻介绍所': 'marriage bureaus', '谈判场所': 'negotiation venues', '门户': 'doorways',
  '中间地带': 'middle ground', '苇塘': 'reed ponds', '葱岭': 'onion ridges', '契约': 'contracts',
  '信函': 'letters', '低矮的柜子': 'low cabinets', '箱子': 'boxes', '结婚证书': 'marriage certificates',
  '信印': 'seals of trust', '果品': 'fruits', '衣囊': 'clothing bags', '轮船': 'steamships',
  '筵会': 'feasts', '白糖': 'white sugar', '证据': 'evidence', '兔子': 'rabbits', '鸳鸯': 'mandarin ducks',
  '麻雀': 'sparrows', '蜻蜓': 'dragonflies', '蝴蝶': 'butterflies', '蝗虫': 'locusts', '燕子': 'swallows',
  '大雁': 'wild geese', '天鹅等一切群居双聚的动物': 'swans & all flocking, pairing animals',
  '竹笋': 'bamboo shoots', '柳树': 'willows', '合伙经营': 'joint ventures', '商业谈判': 'business negotiations',
  '团聚': 'reunion', '和合': 'union & harmony', '通信': 'correspondence', '主和合成事': 'augurs union & success',
  '利婚姻合作交易': 'good for marriage, partnership & trade', '凡事合而不分': 'all things join, not part',
  '多种颜色的组合': 'multicoloured combinations', '阴雨连绵': 'persistent rains',
});

/* Batch 6 — final mop-up. */
Object.assign(window.QMS_TERMS_EN, {
  '美容': 'beauty care', '生产': 'production', '建筑': 'buildings', '备注': 'note',
  '普照四方': 'shining on all quarters', '雄心万丈': 'boundless ambition', '自信满满': 'brimming confidence',
  '女神': 'goddesses', '旺于春木': 'prospers in spring Wood', '相于冬水': 'assisted in winter Water',
  '休于夏火': 'rests in summer Fire', '囚于季夏土': 'trapped in late-summer Earth', '死于秋金': 'dies in autumn Metal',
  '强权执法机关': 'forceful law agencies', '与车辆有密切关联的事': 'vehicle-related matters',
  '春天': 'spring', '风': 'wind', '押保': 'guarantors', '媒医': 'matchmakers & healers',
  '高尚': 'noble-minded', '面': 'the face', '突破': 'breakthrough', '小型金属物品': 'small metal items',
  '破坏': 'destruction', '烟火': 'fireworks', '古董': 'antiques', '春风': 'spring breeze',
  '名人居所': 'celebrity residences', '占断特征': 'divination traits', '潮湿的地方': 'damp places',
  '和风': 'gentle breeze', '门': 'doors', '窗': 'windows', '好斗': 'combative', '音乐': 'music',
  '有魄力': 'bold & decisive', '使用条件': 'conditions of use', '阳遁': 'Yang Dun', '阴遁': 'Yin Dun',
  '阴谋': 'plots', '暗中交易': 'covert deals', '慈善仁慈': 'charitable & kind', '慈善': 'charity',
  '外貌': 'appearance', '刑场': 'execution grounds', '孝服': 'mourning garb', '人物例': 'example figures',
  '思想不开放': 'closed-minded', '合作': 'cooperation', '医疗器械': 'medical devices',
});
